-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	
-- // MÓDULO:			CLIENTE_TMK
-- // OPERACIÓN:		LIBERACIÓN / CARGA INICIAL
-- ////////////////////////////////////////////////////////////// 
-- // Autor:			
-- // Fecha creación:	
-- ////////////////////////////////////////////////////////////// 

USE [LIQ19_Liquidaciones_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTE_TMK]') AND type in (N'U'))
	DELETE	FROM [dbo].[CLIENTE_TMK]
GO


-- //////////////////////////////////////////////////////////////
-- //				CI - CLIENTE_TMK
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_CLIENTE_TMK]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_CLIENTE_TMK]
GO

CREATE PROCEDURE [dbo].[PG_CI_CLIENTE_TMK]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ======================================
	@PP_K_CLIENTE_TMK			INT,
	@PP_D_CLIENTE_TMK			VARCHAR(255),
	@PP_C_CLIENTE_TMK			VARCHAR(500),
	@PP_S_CLIENTE_TMK			VARCHAR(10),	
	-- =====================================
	@PP_K_ESTATUS_CLIENTE_TMK	INT,
	@PP_K_ALERTA_VENTA			INT,
	@PP_K_TIPO_CLIENTE_TMK		INT,
	-- ======================================
	@PP_NOMBRE					VARCHAR(100),
	@PP_APELLIDO_PATERNO		VARCHAR(100),
	@PP_APELLIDO_MATERNO		VARCHAR(100),
	@PP_RFC						VARCHAR(100),
	-- ======================================
	@PP_CALLE					VARCHAR(100),
	@PP_NUMERO_EXTERIOR			VARCHAR(100),
	@PP_NUMERO_INTERIOR			VARCHAR(100),
	@PP_ENTRE_CALLE				VARCHAR(100),
	@PP_Y_CALLE					VARCHAR(100),
	@PP_COLONIA					VARCHAR(100),
	-- ======================================
	@PP_MUNICIPIO				VARCHAR(100),
	@PP_ESTADO					VARCHAR(100),
	@PP_CP						VARCHAR(100)	
AS				
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_CLIENTE_TMK
							FROM	[CLIENTE_TMK]
							WHERE	K_CLIENTE_TMK=@PP_K_CLIENTE_TMK

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO CLIENTE_TMK
			(	K_CLIENTE_TMK,				D_CLIENTE_TMK,
				C_CLIENTE_TMK,				S_CLIENTE_TMK,	
				-- ==========================================
				K_ESTATUS_CLIENTE_TMK,		K_ALERTA_VENTA,
				K_TIPO_CLIENTE_TMK,
				-- ==========================================
				NOMBRE,					
				APELLIDO_PATERNO,			APELLIDO_MATERNO,	
				RFC,
				-- ==========================================
				CALLE,					
				NUMERO_EXTERIOR,			NUMERO_INTERIOR,
				ENTRE_CALLE,				Y_CALLE,				
				COLONIA,
				-- ==========================================			
				MUNICIPIO,					ESTADO,					
				CP,		
				-- ==========================================
				K_USUARIO_ALTA,				F_ALTA,
				K_USUARIO_CAMBIO,			F_CAMBIO,
				L_BORRADO,
				K_USUARIO_BAJA,				F_BAJA					)
		VALUES	
			(	@PP_K_CLIENTE_TMK,			@PP_D_CLIENTE_TMK,
				@PP_C_CLIENTE_TMK,			@PP_S_CLIENTE_TMK,
				-- ==========================================
				@PP_K_ESTATUS_CLIENTE_TMK,	@PP_K_ALERTA_VENTA,
				@PP_K_TIPO_CLIENTE_TMK,
				-- ==========================================
				@PP_NOMBRE,				
				@PP_APELLIDO_PATERNO,		@PP_APELLIDO_MATERNO,	
				@PP_RFC,
				-- ==========================================
				@PP_CALLE,					
				@PP_NUMERO_EXTERIOR,		@PP_NUMERO_INTERIOR,
				@PP_ENTRE_CALLE,			@PP_Y_CALLE,			
				@PP_COLONIA,	
				-- ==========================================		
				@PP_MUNICIPIO,				@PP_ESTADO,				
				@PP_CP,			
				-- ==========================================
				@PP_K_USUARIO_ACCION,	GETDATE(),
				@PP_K_USUARIO_ACCION,	GETDATE(),
				0,
				NULL, NULL										)
	ELSE
		UPDATE	CLIENTE_TMK
		SET		
				K_CLIENTE_TMK			= @PP_K_CLIENTE_TMK,			 				
				D_CLIENTE_TMK			= @PP_D_CLIENTE_TMK,
				C_CLIENTE_TMK			= @PP_C_CLIENTE_TMK,							
				S_CLIENTE_TMK			= @PP_S_CLIENTE_TMK,	
				-- ===========================
				K_ESTATUS_CLIENTE_TMK	= @PP_K_ESTATUS_CLIENTE_TMK,	
				K_ALERTA_VENTA		= @PP_K_ALERTA_VENTA,
				K_TIPO_CLIENTE_TMK		= @PP_K_TIPO_CLIENTE_TMK,
				-- ===========================
				NOMBRE					= @PP_NOMBRE,									
				APELLIDO_PATERNO		= @PP_APELLIDO_PATERNO,		
				APELLIDO_MATERNO		= @PP_APELLIDO_MATERNO,	
				RFC						= @PP_RFC,
				-- ===========================
				CALLE					= @PP_CALLE,									
				NUMERO_EXTERIOR			= @PP_NUMERO_EXTERIOR,			
				NUMERO_INTERIOR			= @PP_NUMERO_INTERIOR,
				ENTRE_CALLE				= @PP_ENTRE_CALLE,					
				Y_CALLE					= @PP_Y_CALLE,							
				COLONIA					= @PP_COLONIA,	
				-- ===========================					
				MUNICIPIO				= @PP_MUNICIPIO,							
				ESTADO					= @PP_ESTADO,									
				CP						= @PP_CP,	
				-- ===========================			
				[K_USUARIO_CAMBIO]		= @PP_K_USUARIO_ACCION, 
				[F_CAMBIO]				= GETDATE() 
		WHERE	K_CLIENTE_TMK=@PP_K_CLIENTE_TMK
	-- =========================================================	
GO


-- ===============================================
SET NOCOUNT ON
-- ===============================================

/*

EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 0, 'SIN CLIENTE CYC', 'SIN CLIENTE CYC', 'SINCLIENTE', 1, 0, 2, '', '', '', '', '', '', '', '', '', '', '', '', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 10, 'FONDO UNIDO CHIHUAHUA,A.C.  ', '', '', 1, 0, 2, 'FONDO UNIDO CHIHUAHUA,A.C.', '', '', '', 'CALLE CAYETANO LOPEZ', '543', '', 'AV. INSURGENTES', '', 'BUROCRATA 2A SECC', 'JUAREZ', 'JALISCO', '32340'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 11, 'HOGARES DE BIENESTAR Y DESARROLLO INFANTIL,A.C.  ', '', '', 1, 0, 2, 'HOGARES DE BIENESTAR Y DESARROLLO INFANTIL,A.C.', '', '', '', 'ORTIZ DE CAMPOS', '3122', '', '', '', 'SAN FELIPE', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 13, 'GUARDERIA PARQUE RIO BRAVO,A.C.  ', '', '', 1, 0, 2, 'GUARDERIA PARQUE RIO BRAVO,A.C.', '', '', '', 'MANUEL SANDOVAL VALLARTA', '590', '', '', '', 'PARQUE INDUSTRIAL RIO BRAVO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 14, 'DESARROLLO COMUNITARIO STA MARIA,A.C.  ', '', '', 1, 0, 2, 'DESARROLLO COMUNITARIO STA MARIA,A.C.', '', '', '', 'BLVD.ZARAGOZA', '410', '', '', '', 'FRACC CD MODERNA', 'JUAREZ', 'JALISCO', '32670'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 16, 'ESTANCIA INFANTIL MALU,S.C.  ', '', '', 1, 0, 2, 'ESTANCIA INFANTIL MALU,S.C.', '', '', '', 'DELICIAS', '6332', '', '', '', 'NVO HIPODROMO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 17, 'CASAS DE LIBERTAD BETHEL  ', '', '', 1, 0, 2, 'CASAS DE LIBERTAD BETHEL', '', '', '', 'SIERRA MINERAS', '5429', '', '', '', 'LA CUESTA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 24, 'COMERCIALIZADORA ALPACEL SA DE CV  ', '', '', 1, 0, 2, 'COMERCIALIZADORA ALPACEL SA DE CV', '', '', '', '5 DE MAYO', '176', '', '', '', 'CENTRO', 'ZAMORA', 'JALISCO', '59624'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 25, 'QAR DEL NOROESTE SA DE CV  ', '', '', 1, 0, 2, 'QAR DEL NOROESTE SA DE CV', '', '', '', 'AVE. VICENTE GUERRERO', '102', '', '', '', 'ZONA CENTRO', 'JUAREZ', 'JALISCO', '32000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 37, 'DURAN OROZCO ROGELIO', 'OROZCO', '', 1, 0, 2, 'DURAN', 'OROZCO', 'ROGELIO', '', 'ONCE', '6504', '', '', '', 'LA PRESA', 'JUAREZ', 'JALISCO', '32688'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 43, 'BEEF INTERNACIONAL,S.A.DE C.V.  ', '', '', 1, 0, 2, 'BEEF INTERNACIONAL,S.A.DE C.V.', '', '', '', 'AVE. UNIVERSIDAD', '1200', '', '', '', 'XOCO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 49, 'CLIMAS Y PROYECTOS LEYCO, S.A DE C.V  ', '', '', 1, 0, 2, 'CLIMAS Y PROYECTOS LEYCO, S.A DE C.V', '', '', '', 'AVE. VALENTIN FUENTES', '1181A', '', 'AV. DE LA RAZA', '', 'PARTIDO LAS FUENTES CHIHUAHU', 'JUAREZ', 'JALISCO', '32377'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 56, 'SUPERMERCADO GONZALEZ DE ALTAVISTA S.A. DE C.V.  ', '', '', 1, 0, 2, 'SUPERMERCADO GONZALEZ DE ALTAVISTA S.A. DE C.V.', '', '', '', 'BLVD. FRONTERIZO', '3530', '', 'BARRANCO AZUL', '', 'ALTAVISTA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 61, 'PROVEEDORA DE MATERIAL INDUSTRIAL SA DE CV  ', '', '', 1, 0, 2, 'PROVEEDORA DE MATERIAL INDUSTRIAL SA DE CV', '', '', '', 'PABLO GOMEZ', '11233', '', '', '', 'LUCIO CABA?AS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 62, 'EXPORT PALLETS DE MEXICO,S.A. DE C.V.  ', '', '', 1, 0, 2, 'EXPORT PALLETS DE MEXICO,S.A. DE C.V.', '', '', '', 'WEB:CONSUELO CABRERA.', 'SN', '', 'LA BOQUILLA', '', 'ND', 'JUAREZ', 'JALISCO', '32680'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 64, 'ALFA CRONOS,S.A. DE C.V.  ', '', '', 1, 0, 2, 'ALFA CRONOS,S.A. DE C.V.', '', '', '', 'HERMANOS ESCOBAR', '7046', '8910', '', '', 'PARQUE INDUSTRIAL OMEGA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 77, 'ALMACENES DISTRIBUIDORES DE LA FRONTERA,S.A. DE C.V.  ', '', '', 1, 0, 2, 'ALMACENES DISTRIBUIDORES DE LA FRONTERA,S.A. DE C.V.', '', '', '', 'C. PLUTARCO ELIAS CALLES', '744', '', '', '', 'COL. PROGRESISTA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 96, 'BERMUDEZ CUARON JAIME  ', '', '', 1, 0, 2, 'BERMUDEZ CUARON JAIME', '', '', '', 'AV. 16 DE SEPTIEMBRE', '1559', '', '', '', 'COL. PARTIDO ROMERO', 'JUAREZ', 'JALISCO', '32030'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 102, 'MINNE SA DE CV  ', '', '', 1, 0, 2, 'MINNE SA DE CV', '', '', '', 'AV. DE LA RAZA', '4946', '', '', '', 'EL COLEGIO', 'JUAREZ', 'JALISCO', '32350'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 109, 'INDUSTRIALIZADORA DE ALIMENTOS DEL CAMPO S.A. DE C.V. JONA ', 'JONA', '', 1, 0, 2, 'INDUSTRIALIZADORA DE ALIMENTOS DEL CAMPO S.A. DE C.V.', 'JONA', '', '', 'ETHEL CUERVO HUERTA', '7620', '', '', '', 'COL. INDEPENDENCIA NO. 2', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 111, 'ULTRA POWDER COATING S DE RL DE CV  ', '', '', 1, 0, 2, 'ULTRA POWDER COATING S DE RL DE CV', '', '', '', 'PEDRO MENESES HOYOS', '6470', '4', '', '', 'LA CUESTA', 'JUAREZ', 'JALISCO', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 130, 'PROMOTORES MEXICANOS DE LA EDUCACION AC  ', '', '', 1, 0, 2, 'PROMOTORES MEXICANOS DE LA EDUCACION AC', '', '', '', 'CAMINO VIEJO SAN JOSE', '10051', '', 'URN', '', 'PARTIDO SENECU', 'JUAREZ', 'JALISCO', '32459'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 138, 'CONSTRUCTORA ANGLO, S.A DE C.V  ', '', '', 1, 0, 2, 'CONSTRUCTORA ANGLO, S.A DE C.V', '', '', '', 'AV. TEOFILO BORUNDA', '7751', '301', '', '', 'FRACC. BOSQUES DEL SOL', 'JUAREZ', 'JALISCO', '32616'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 139, 'GEXIQ, S.A. DE C.V.  ', '', '', 1, 0, 2, 'GEXIQ, S.A. DE C.V.', '', '', '', 'AVE. PASEO TRIUNFO DE LA REPUBLICA', '3304', '404', '', '', 'PARTIDO ESCOBEDO', 'JUAREZ', 'JALISCO', '32330'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 150, 'TRITURADORA AGUILA,S.A. DE C.V.  ', '', '', 1, 0, 2, 'TRITURADORA AGUILA,S.A. DE C.V.', '', '', '', 'AVE PASEO TRIUNFO DE LA REPUBLICA', '3304', '404', '', '', 'PARTIDO ESCOBEDO', 'JUAREZ', 'JALISCO', '32330'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 161, 'HERMES CONSTRUCCION Y DISEÑO, S.A. DE C.V.  ', '', '', 1, 0, 2, 'HERMES CONSTRUCCION Y DISEÑO, S.A. DE C.V.', '', '', '', 'LUIS L. LEON', '9651', '', '', '', 'PARQUE INDUSTRIAL ANTONIO J.', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 163, 'CONSTRUCTORA JEBE S.A. DE C.V.  ', '', '', 1, 0, 2, 'CONSTRUCTORA JEBE S.A. DE C.V.', '', '', '', 'LUIS L. LEON/CHEQUE', '9651', '', 'FIRMA JOSE/RUBEN', '', 'PARQUE IND. ANTONIO J. BERMU', 'JUAREZ', 'JALISCO', '32400'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 167, 'OCHOA COMERCIAL, S.A DE C.V  ', '', '', 1, 0, 2, 'OCHOA COMERCIAL, S.A DE C.V', '', '', '', 'PROL. REFORMA', '3131', '', '', '', 'COL. REFORMA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 168, 'LA VICTORIA NUEVA SA DE CV  ', '', '', 1, 0, 2, 'LA VICTORIA NUEVA SA DE CV', '', '', '', 'MERIDA', '948', 'SUR', 'NIÑOES HEROES', '', 'COL. EX-HIPODROMO', 'JUAREZ', 'JALISCO', '32040'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 172, 'FRANCISCO ROJERO VALENZUELA', 'ROJERO', '', 1, 0, 2, 'FRANCISCO', 'ROJERO', 'VALENZUELA', '', 'C.TUNA', '6274', '', 'TORT. AZTECA', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 176, 'PISOS Y AZULEJOS DE LA FRONTERA,S.A. DE C.V.  ', '', '', 1, 0, 2, 'PISOS Y AZULEJOS DE LA FRONTERA,S.A. DE C.V.', '', '', '', 'CARR.PANAMERICANA', '5858', '', '', '', 'FRACC DEL REAL', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 179, 'NADRO,S.A.P.I. DE C.V.  ', '', '', 1, 0, 2, 'NADRO,S.A.P.I. DE C.V.', '', '', '', 'AMERICA LATINA', '7314', '', 'GOMEZ MORIN', 'CAMPEROS', 'NOMBRE DE DIOS', 'CHIHUAHUA', 'JALISCO', '31110'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 184, 'NIASA MEXICO S.A DE C.V  ', '', '', 1, 0, 2, 'NIASA MEXICO S.A DE C.V', '', '', '', 'AVENIDA PEDRO RAMIREZ VAZQUEZ', '200-1', 'PISO 8', '', '', 'SAN PEDRO GARZA GARCIA', 'SAN PEDRO GARZA GARCIA', 'JALISCO', '66269'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 187, 'HILDA RAMIREZ CARBALLO', 'RAMIREZ', '', 1, 0, 2, 'HILDA', 'RAMIREZ', 'CARBALLO', '', 'NUEVA POLITICA MEXICANA', '5012', '', 'RANCHO EL TERRERO', 'AV. AGUA CALIENTE', 'LUIS DONALDO COLOSIO', 'JUAREZ', 'JALISCO', '32663'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 188, 'ALTEC PURIFICACION,S.A. DE C.V.  ', '', '', 1, 0, 2, 'ALTEC PURIFICACION,S.A. DE C.V.', '', '', '', 'PLUTARCO E.CALLES NTE.', '754', '', '', '', 'PROGRESISTA', 'JUAREZ', 'JALISCO', '32310'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 190, 'LIMPIEZA DE SISTEMAS HIDRAULICOS DE JUAREZ, S.A DE C.V  ', '', '', 1, 0, 2, 'LIMPIEZA DE SISTEMAS HIDRAULICOS DE JUAREZ, S.A DE C.V', '', '', '', 'BLVD. FRANCISCO VILLARREAL', '11540', '', 'R-1', '', 'PARTIDO SENECU', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 193, 'ELECTRO TEC S.A  ', '', '', 1, 0, 2, 'ELECTRO TEC S.A', '', '', '', 'HENRY DUNANT', '5155', '', 'PLUTARCO ELIAS CALLES', '', 'PROGRESISTA', 'JUAREZ', 'JALISCO', '32310'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 198, 'ACEROS Y PERFILES DE CIUDAD JUAREZ, S.A. DE C.V.  ', '', '', 1, 0, 2, 'ACEROS Y PERFILES DE CIUDAD JUAREZ, S.A. DE C.V.', '', '', '', 'ISAURA ESPINOZA', '7703', '', '', '', 'INDEPENDENCIA No 2', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 201, 'MATERIALES RIO GRANDE,S.A. DE C.V.  ', '', '', 1, 0, 2, 'MATERIALES RIO GRANDE,S.A. DE C.V.', '', '', '', 'PASEO TRIUNFO DE LA REPUBLICA', '3535', '', 'AV. DEL CHARRO', '', 'PARTIDO DIAZ', 'JUAREZ', 'JALISCO', '32320'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 211, 'PROCESADORA AGROINDUSTRIAL DEL NORTE S DE PR DE RL DE CV  ', '', '', 1, 0, 2, 'PROCESADORA AGROINDUSTRIAL DEL NORTE S DE PR DE RL DE CV', '', '', '', 'CUARTA', '3207', '', '', '', 'SANTA ROSA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 222, 'FRANCISCO CRISTOBAL SEGURA DE LIRA', 'SEGURA', '', 1, 0, 2, 'FRANCISCO CRISTOBAL', 'SEGURA', 'DE LIRA', '', 'FRANCISCO JAVIER MINA', '493', '', 'CASA SEGURA', '', 'CENTRO', 'JUAREZ', 'JALISCO', '32000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 243, 'COLEGIO DE BACHILLERES DEL ESTADO DE CHIHUAHUA  ', '', '', 1, 0, 2, 'COLEGIO DE BACHILLERES DEL ESTADO DE CHIHUAHUA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 245, 'UNIVERSIDAD AUTONOMA DE CIUDAD JUAREZ  ', '', '', 1, 0, 2, 'UNIVERSIDAD AUTONOMA DE CIUDAD JUAREZ', '', '', '', 'AVENIDA PLUTARCO ELIAS CALLES', '1210', '', '', '', 'FOVISTE CHAMIZAL', 'JUAREZ', 'JALISCO', '32310'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 249, 'CONSTRUCTODO DE JUAREZ, S.A DE C.V  ', '', '', 1, 0, 2, 'CONSTRUCTODO DE JUAREZ, S.A DE C.V', '', '', '', 'CARRETERA PANAMERICANA', '6415', '', '', '', 'FRACC. LOMAS DE SAN JOSE', 'JUAREZ', 'JALISCO', '32680'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 250, 'CENTRAL DE MANGUERAS Y CONEXIONES DE CIUDAD JUAREZ SA DE CV  ', '', '', 1, 0, 2, 'CENTRAL DE MANGUERAS Y CONEXIONES DE CIUDAD JUAREZ SA DE CV', '', '', '', 'AVENIDA DE LAS TORRES', '1151', '', 'HENEQUEN', '', 'TORRES DEL PRI', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 252, 'HOME DEPOT MEXICO S DE RL DE CV  ', '', '', 1, 0, 2, 'HOME DEPOT MEXICO S DE RL DE CV', '', '', '', 'RICARDO MARGAIN ZOZAYA', '605', '', 'SIMONA BARBA', '', 'SANTA ENGRACIA', 'GARCIA', 'JALISCO', '66267'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 254, 'INDUSTRIAS ZARAGOZA, DIV. PROD. MET. S.A DE C.V  ', '', '', 1, 0, 2, 'INDUSTRIAS ZARAGOZA, DIV. PROD. MET. S.A DE C.V', '', '', '', 'CARRETERA PANAMERICANA', 'KM 17', '', '', '', 'COL. NUEVO HIPODROMO', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 256, 'HIDROGAS DE AGUA PRIETA,S.A.  ', '', '', 1, 0, 2, 'HIDROGAS DE AGUA PRIETA,S.A.', '', '', '', 'CARR.NACOZARI KM 3', 'SN', '', '', '', 'ND', 'AGUA PRIETA', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 257, 'DESARROLLOS ESMERALDA,S.A. DE C.V. DES. INMOBILIARIOS CAMPOS ELIS ', 'DES. INMOBILIARIOS CAMPOS ELIS', '', 1, 0, 2, 'DESARROLLOS ESMERALDA,S.A. DE C.V.', 'DES. INMOBILIARIOS CAMPOS ELIS', '', '', 'AV.TECNOLOGICO', '900', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 258, 'GAS COMERCIAL DE NUEVO CASAS GRANDES S.A.  ', '', '', 1, 0, 2, 'GAS COMERCIAL DE NUEVO CASAS GRANDES S.A.', '', '', '', 'CAMINO SUECO-NUEVO CASAS GRANDES KM.', 'SN', '', '', '', 'NUEVO CASAS GRANDES', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 260, 'ASESORIA Y SERV.PROFESIONALES TECNICOS Y ADMVOS,S.A.DE C.V.  ', '', '', 1, 0, 2, 'ASESORIA Y SERV.PROFESIONALES TECNICOS Y ADMVOS,S.A.DE C.V.', '', '', '', 'CARR.PANAMERICANA', 'K 17.5', '', '', '', 'NVO HIPODROMO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 261, 'GAS BUTEP, S.A.  ', '', '', 1, 0, 2, 'GAS BUTEP, S.A.', '', '', '', 'MORELOS', '51', '', '', '', 'COL. CENTRO', 'TEPATITLAN', 'JALISCO', '47600'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 262, 'ENRIQUE ZARAGOZA ', 'ZARAGOZA', '', 1, 0, 2, 'ENRIQUE', 'ZARAGOZA', '', '', 'CAMPOS ELISEOS', 'SN', '', 'CAMPOS ELISEOS', 'VILLITA', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 268, 'APPLEMEX, S.A. DE C.V.  ', '', '', 1, 0, 2, 'APPLEMEX, S.A. DE C.V.', '', '', '', 'AV. CAMPOS ELISEOS', '9345', '', '', '', 'CAMPOS ELISEOS', 'JUAREZ', 'JALISCO', '32472'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 269, 'TOMAS ZARAGOZA ', 'ZARAGOZA', '', 1, 0, 2, 'TOMAS', 'ZARAGOZA', '', '', 'VERSALLES', 'SN', '', '', '', 'CAMPOS ELISEOS', 'JUAREZ', 'JALISCO', '32472'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 271, 'MARIO SANCHEZ ', 'SANCHEZ', '', 1, 0, 2, 'MARIO', 'SANCHEZ', '', '', 'PANAMERICANA', '17.5', '', '', '', 'NUEVO HIPODROMO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 274, 'FUNERARIA LA PAZ, S.A. DE C.V.  ', '', '', 1, 0, 2, 'FUNERARIA LA PAZ, S.A. DE C.V.', '', '', '', 'AVE. 16 DE SEPTIEMBRE', '887', 'OTE', 'MARMOLERIA', '', 'COL. PARTIDO ROMERO', 'JUAREZ', 'JALISCO', '32030'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 276, 'INSTITUTO MEXICANO DEL SEGURO SOCIAL  ', '', '', 1, 0, 2, 'INSTITUTO MEXICANO DEL SEGURO SOCIAL', '', '', '', 'C.PORFIRIO PARRA ESQ. CON', 'SOTO', '', '', '', 'COL. FCO. I MADERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 294, 'INSTITUTO PATRIA Y CULTURA AC CENTRO CRISTIANO VINO NUEVO, A ', 'CENTRO CRISTIANO VINO NUEVO, A', '', 1, 0, 2, 'INSTITUTO PATRIA Y CULTURA AC', 'CENTRO CRISTIANO VINO NUEVO, A', '', '', 'C. MELQUIADES ALANIS', '5825', '', '', '', 'ALAMOS DE SAN LORENZO', 'JUAREZ', 'JALISCO', '32320'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 348, 'MONARCH LITHO DE MEXICO,S.A. DE C.V.  ', '', '', 1, 0, 2, 'MONARCH LITHO DE MEXICO,S.A. DE C.V.', '', '', '', 'PROLG.HENRY DUNANT', '6451', '', '', '', 'PARQUE INDUSTRIAL OMEGA', 'JUAREZ', 'JALISCO', '32410'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 349, 'NORTH AMERICAN MAILING SERVICES,S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'NORTH AMERICAN MAILING SERVICES,S. DE R.L. DE C.V.', '', '', '', 'AVE. AGUILA CORONADA', '19491', '', '', '', 'PARQUE INDUSTRIAL BAJA MAQ.', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 359, 'OPTRON DE MEXICO, S.A DE C.V  ', '', '', 1, 0, 2, 'OPTRON DE MEXICO, S.A DE C.V', '', '', '', 'C. RIO BRAVO', '1551', '', '', '', 'COL. PARQUE INDUSTRIAL RIO B', 'JUAREZ', 'JALISCO', '32557'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 361, 'LOGTEC,S.A. DE C.V.  ', '', '', 1, 0, 2, 'LOGTEC,S.A. DE C.V.', '', '', '', 'ENRICO FERMI', '1450', '', '', '', 'PARQUE INDUSTRIAL RIO BRAVO', 'JUAREZ', 'JALISCO', '32557'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 362, 'VICTORY PACKAGING DE MEXICO,S.DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'VICTORY PACKAGING DE MEXICO,S.DE R.L. DE C.V.', '', '', '', 'AV JUAN PABLO II', '2750', '', 'LIBRAMIENTO', 'TALAMAS CAMANDARI', 'PROFESORA MARIA MARTINEZ', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 363, 'TECNOLOGIA DE ILUMINACION AUTOMOTRIZ, S.A DE C.V  ', '', '', 1, 0, 2, 'TECNOLOGIA DE ILUMINACION AUTOMOTRIZ, S.A DE C.V', '', '', '', 'AV. DEL CHARRO', '1750', '', '', '', 'COL. PARTIDO ESCOBEDO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 379, 'TORO COMPANY DE MEXICO S DE RL DE CV  ', '', '', 1, 0, 2, 'TORO COMPANY DE MEXICO S DE RL DE CV', '', '', '', 'BLVD. INDEPENDENCIA', '2159', '', 'LIBRE', '', 'P. IND. LAS AMERICAS', 'JUAREZ', 'JALISCO', '32695'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 382, 'INTERMEX MANUFACTURA SA DE CV  ', '', '', 1, 0, 2, 'INTERMEX MANUFACTURA SA DE CV', '', '', '', 'AV. PARQUE IND. JUAREZ ENTRE HORNOS', '3551', '', 'MIGUEL DE LA MADRID', '', 'PARQUE IND. CD. JUAREZ', 'CHIHUAHUA', 'JALISCO', '32630'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 386, 'SALTER LABS DE MEXICO SA DE CV  ', '', '', 1, 0, 2, 'SALTER LABS DE MEXICO SA DE CV', '', '', '', 'AV. SANTOS DUMONT', '6630', '', '', '', 'PARQUE INDUSTRIAL PANAMERICA', 'JUAREZ', 'JALISCO', '32695'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 389, 'SELICSA SA DE CV  ', '', '', 1, 0, 2, 'SELICSA SA DE CV', '', '', '', 'CALLE LOS BRACEROS', '11540', '', 'TOLVA,MONTACARGAS,EDIFICIO,LAVADO', '', 'COLONIA PARTIDO SENECU', 'JUAREZ', 'JALISCO', '32350'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 392, 'BUSSMANN S.DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'BUSSMANN S.DE R.L. DE C.V.', '', '', '', 'PROLONGACION HNOS. ESCOBAR', '7750', '', '4 SIGLOS', 'VALLE DE VERSALLES', 'PARTIDO MANUEL DOBLADO', 'JUAREZ', 'JALISCO', '32310'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 393, 'ANSELL EDMONT INDUSTRIAL INC. S.A. DE C.V.  ', '', '', 1, 0, 2, 'ANSELL EDMONT INDUSTRIAL INC. S.A. DE C.V.', '', '', '', 'ANTONIO J. BERMUDEZ', 'SN', '', 'ANTONIO J. BERMUDEZ', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 394, 'AMN INTERNATIONAL S.A. DE C.V.  ', '', '', 1, 0, 2, 'AMN INTERNATIONAL S.A. DE C.V.', '', '', '', 'AVENIDA DE LA RAZA', '5890', '', 'AV DEL CHARRO', '', 'PARTIDO DOBLADO', 'JUAREZ', 'JALISCO', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 397, 'ANSELL PERRY DE MEXICO S.A. DE C.V.  ', '', '', 1, 0, 2, 'ANSELL PERRY DE MEXICO S.A. DE C.V.', '', '', '', 'ISAAC NEWTON', '1650', '', 'TIENE SELLO', '', 'PARQUE INDUSTRIAL BERMUDEZ', 'JUAREZ', 'JALISCO', '32470'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 405, 'LAU INDUSTRIES  ', '', '', 1, 0, 2, 'LAU INDUSTRIES', '', '', '', 'TAPIOCA', '5455', '', 'AV. PASEO DE LA VICTORIA', 'RUSKIN', 'AEROPUERTO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 408, 'SPAT MAIL, S.A DE C.V  ', '', '', 1, 0, 2, 'SPAT MAIL, S.A DE C.V', '', '', '', 'AV. QUINTA NORTE', '301', '', 'P. ELIAS CALLES', 'MONTOYA', 'CENTRO', 'DELICIAS', 'JALISCO', '33000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 410, 'MUNICIPIO DE JUAREZ  ', '', '', 1, 0, 2, 'MUNICIPIO DE JUAREZ', '', '', '', 'FRANCISCO VILLA', '950 NORTE', '', 'VICENTE GUERRERO', '', 'ZONA CENTRO', 'JUAREZ', 'JALISCO', '32000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 420, 'PRODUCTOS SECUNDARIOS RECICLABLES, S.A. DE C.V  ', '', '', 1, 0, 2, 'PRODUCTOS SECUNDARIOS RECICLABLES, S.A. DE C.V', '', '', '', 'EJE VIAL JUAN GABRIEL', '3550', '', '', '', '5 DE MAYO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 426, 'JOAQUIN SANSON BERNAL LARA', 'BERNAL', '', 1, 0, 2, 'JOAQUIN SANSON', 'BERNAL', 'LARA', '', 'TORO BRONCO AMERICAS', '1', '', 'CASA / PINO SUAREZ', 'SIERRA SAN CARLOS NO SURTIR', 'LA CUESTA', 'JUAREZ', 'JALISCO', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 429, 'ARMENDARIZ LETICIA  ', '', '', 1, 0, 2, 'ARMENDARIZ LETICIA', '', '', '', 'AV. PANAMERICANA', '5048', '', '', '', 'PARTIDO IGLESIAS', 'AHUMADA', 'CHIHUAHUA', '32390'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 444, 'MARISCOS PACIFICO  ', '', '', 1, 0, 2, 'MARISCOS PACIFICO', '', '', '', 'EJERCITO NACIONAL', '6227', '', '', '', 'MISIONES DEL PORTAL', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 460, 'FUN CREATORS, S.A. DE C.V.  ', '', '', 1, 0, 2, 'FUN CREATORS, S.A. DE C.V.', '', '', '', 'AV. VALLARTA', '3959', '', '', '', 'DON BOSCO VALLARTA', 'ZAPOPAN', 'JALISCO', '45049'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 496, 'SANDRA GARCIA RAMOS', 'GARCIA', '', 1, 0, 2, 'SANDRA', 'GARCIA', 'RAMOS', '', 'MANUEL J CLOUTHIER', '1509', '', 'TORO BRONCO', '', 'SALVARCAR', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 503, 'RENE HERNANDEZ VILLA', 'HERNANDEZ', '', 1, 0, 2, 'RENE', 'HERNANDEZ', 'VILLA', '', 'AVE. DE LOS AZTECAS', '7215', '', 'POPEYES', '', 'MORELOS', 'JUAREZ', 'JALISCO', '32670'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 505, 'RESTAURANTES Y SERVICIOS FRONTERIZOS,S.A DE C.V  ', '', '', 1, 0, 2, 'RESTAURANTES Y SERVICIOS FRONTERIZOS,S.A DE C.V', '', '', '', 'CARRETERA NACIONAL KM 10', 'SN', '', '', '', 'COL. ENRIQUE CARDENAS GONZAL', 'NUEVO LAREDO', 'TAMAULIPAS', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 515, 'AUTOTRANSPORTES PARA LA INDUSTRIA MAQUILADORA, S.A DE C.V.  ', '', '', 1, 0, 2, 'AUTOTRANSPORTES PARA LA INDUSTRIA MAQUILADORA, S.A DE C.V.', '', '', '', 'PROLONGACION AVE REFORMA', '2848', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 532, 'TRANSPORTADORA SILZA S.A DE C.V  ', '', '', 1, 0, 2, 'TRANSPORTADORA SILZA S.A DE C.V', '', '', '', 'AV. SN JOSE', '11', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 554, 'FLETES MEXICO CHIHUAHUA,S.A. DE C.V.  ', '', '', 1, 0, 2, 'FLETES MEXICO CHIHUAHUA,S.A. DE C.V.', '', '', '', 'CARR.PANAMERICANA', '9760', '', '', '', 'PREDIO ZACATE BLANCO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 567, 'VILLALOBOS ALDRETE GABRIEL OCTAVIO BAR DOÑA ANA ', 'BAR DOÑA ANA', '', 1, 0, 2, 'VILLALOBOS ALDRETE GABRIEL OCTAVIO', 'BAR DOÑA ANA', '', '', 'AV. EJERCITO NACIONAL', '7930', '', '', '', 'PARTIDO IGLEISAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 578, 'ESTANCIA INFANTIL BAMBI S.C.  ', '', '', 1, 0, 2, 'ESTANCIA INFANTIL BAMBI S.C.', '', '', '', 'PRIVADA DEL VALLE', '985', '', 'GOMEZ MORIN', '', 'ORTIZ RUBIO', 'JUAREZ', 'JALISCO', '32540'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 581, 'EDGAR LUCIO FELIX RASCON', 'FELIX', '', 1, 0, 2, 'EDGAR LUCIO', 'FELIX', 'RASCON', '', 'CARR,JUAREZ PORVENIR', '1520 A', 'A', 'POLLO LISTO GOMEZ MORIN', '', 'FRACC NVO. ZARAGOZA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 582, 'BANCO DE ALIMENTOS  ', '', '', 1, 0, 2, 'BANCO DE ALIMENTOS', '', '', '', 'HORTENCIA LICON', 'SN', '', '', '', 'ESPERANZA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 583, 'CARNITAS DE JUAREZ LAURA IBARRA ', 'LAURA IBARRA', '', 1, 0, 2, 'CARNITAS DE JUAREZ', 'LAURA IBARRA', '', '', 'INDIO ACACITLI', '1058', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 584, 'INTERMODAL MEXICO SA DE CV  ', '', '', 1, 0, 2, 'INTERMODAL MEXICO SA DE CV', '', '', '', 'BOSQUE DE CIRUELOS', '180', 'PISO 6', 'INSURGENTES', 'EJE VIAL J.G', 'BOSQUES DE LAS LOMAS', 'MIGUEL HIDAL', 'JALISCO', '11700'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 585, 'CADENA COMERCIAL OXXO SA DE CV  ', '', '', 1, 0, 2, 'CADENA COMERCIAL OXXO SA DE CV', '', '', '', 'NICOLAS GOGOL', '11363', '', '', '', 'COMPLEJO INDUSTRIAL', 'CHIHUAHUA', 'JALISCO', '31136'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 587, 'COPLASCORP SA DE CV  ', '', '', 1, 0, 2, 'COPLASCORP SA DE CV', '', '', '', 'RAMON RIVERA LARA', '6435', '', '', '', 'INFONAVIT CASAS GRANDES', 'AHUMADA', 'CHIHUAHUA', '32600'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 589, 'DISTRIBUIDORA DE EMPAQUES DEL NORTE S.A. DE C.V.  ', '', '', 1, 0, 2, 'DISTRIBUIDORA DE EMPAQUES DEL NORTE S.A. DE C.V.', '', '', '', 'AV. DE LA RAZA', '4804', '', '', '', 'LOS OLIVOS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 590, 'MARTINEZ HERNANDEZ GERARDO ALFREDO ISLA SARABIA ', 'ISLA SARABIA', '', 1, 0, 2, 'MARTINEZ HERNANDEZ GERARDO ALFREDO', 'ISLA SARABIA', '', '', 'SINALOA', '617', '', 'LA MAS BARATA 3', '', 'FRANCISCO SARABIA', 'JUAREZ', 'JALISCO', '32150'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 591, 'SOCIEDAD COOPERATIVA DE CONSUMO TREJJAN S.C. DE R.L.  ', '', '', 1, 0, 2, 'SOCIEDAD COOPERATIVA DE CONSUMO TREJJAN S.C. DE R.L.', '', '', '', 'AV. WATERFILL', '800', '', '', '', 'INTERNACIONAL', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 593, 'GORDITAS TERE  ', '', '', 1, 0, 2, 'GORDITAS TERE', '', '', '', 'NAHOAS', 'SN', '', 'CARLOS AMAYA', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 594, 'GRUPO ALSEGA S.A. DE C.V. HOTEL DOÑA ANA ', 'HOTEL DOÑA ANA', '', 1, 0, 2, 'GRUPO ALSEGA S.A. DE C.V.', 'HOTEL DOÑA ANA', '', '', 'AVE. EJERCITO NACIONAL', '7930', '', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 595, 'MADERAS Y EMBALAJES ROQUEZA  ', '', '', 1, 0, 2, 'MADERAS Y EMBALAJES ROQUEZA', '', '', '', 'AVE. REFORMA', '3052', '', '', '', 'MELCHOR OCAMPO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 604, 'RAUL HELO BENAVENTE', 'HELO', '', 1, 0, 2, 'RAUL', 'HELO', 'BENAVENTE', '', 'CATALINA DE SAN JUAN', '5366', '', 'PCTOS CARNICOS SEBO', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '32600'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 611, 'BAÑUELOS MARTINEZ CLAUDIA BAÑUELOS MARTINEZ', 'BAÑUELOS', '', 1, 0, 2, 'BAÑUELOS MARTINEZ CLAUDIA', 'BAÑUELOS', 'MARTINEZ', '', 'BRASIL', 'SN', '', 'CHAPULTEPEC', 'TOR.LAS 3 B', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 617, 'NEMESIO SANCHEZ ', 'SANCHEZ', '', 1, 0, 2, 'NEMESIO', 'SANCHEZ', '', '', 'CERRO DE LA PLATA', '6160', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 621, 'ROBERTO CARLOS RONQUILLO GUZMAN', 'RONQUILLO', '', 1, 0, 2, 'ROBERTO CARLOS', 'RONQUILLO', 'GUZMAN', '', 'SIERRA DE DELICIAS', '9031', '', '', '', 'SIERRA GRANDE CHIHUAHUA', 'JUAREZ', 'JALISCO', '32574'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 626, 'MARIA BLANCA CHAVIRA SANDOVAL', 'CHAVIRA', '', 1, 0, 2, 'MARIA BLANCA', 'CHAVIRA', 'SANDOVAL', '', 'ACANTO', '9595', 'FLORESTA', 'FERRETERIA DURAN', '', 'PANAMERICANO JARDIN', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 631, 'ICHEA  ', '', '', 1, 0, 2, 'ICHEA', '', '', '', 'J. ELIGIO MU?OZ', '1910', '', '', '', 'SANTO NI?O', 'CHIHUAHUA', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 632, 'EL SABROSO TACO S.A. DE C.V.  ', '', '', 1, 0, 2, 'EL SABROSO TACO S.A. DE C.V.', '', '', '', 'AVENIDA LOPEZ MATEOS', '1416', '', 'SIMONA BARBA', '', 'MELCHOR OCAMPO', 'JUAREZ', 'JALISCO', '32380'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 633, 'GERMAN CHAVEZ GUTIERREZ', 'CHAVEZ', '', 1, 0, 2, 'GERMAN', 'CHAVEZ', 'GUTIERREZ', '', '23 PROVIDENCIA', '2156', '', 'FERR LA JOYA', '', 'MANUEL J. CLOUHTIER', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 658, 'GRUPO INDUSTRIAL Y COMERCIAL NARVAEZ,S.DE R.L. DE CV.  ', '', '', 1, 0, 2, 'GRUPO INDUSTRIAL Y COMERCIAL NARVAEZ,S.DE R.L. DE CV.', '', '', '', 'MERIDA', '858', '', '', '', 'EX HIPODROMO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 663, 'PROCESADOS REY DAVID S DE RL DE CV  ', '', '', 1, 0, 2, 'PROCESADOS REY DAVID S DE RL DE CV', '', '', '', 'RIO CONCHOS', '1228', '', '', '', 'LOS NOGALES', 'JUAREZ', 'JALISCO', '32350'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 665, 'INMOBILIARIA JORPI DE JUAREZ S.A DE C.V.  ', '', '', 1, 0, 2, 'INMOBILIARIA JORPI DE JUAREZ S.A DE C.V.', '', '', '', 'AV. AMERICAS', '1204', '', '', '', 'LA PLAYA', 'JUAREZ', 'JALISCO', '32300'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 666, 'DESARROLLO EDUCATIVO SAN LUIS GONZAGA A.C. COLEGIO SANTA MARIA ', 'COLEGIO SANTA MARIA', '', 1, 0, 2, 'DESARROLLO EDUCATIVO SAN LUIS GONZAGA A.C.', 'COLEGIO SANTA MARIA', '', '', 'OASIS DE MONGOLIA', '2050', '', '', '', 'PRADERA DE LOS OASIS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 667, 'ACEIGRASAS DE JUAREZ S DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'ACEIGRASAS DE JUAREZ S DE R.L. DE C.V.', '', '', '', 'BLVD. OSCAR FLORES', '5514', '', 'MONTES APENINOS', '', 'LA CUESTA', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 669, 'IMPLEMENTOS DE MANUFACTURAS Y SERVICIOS S.A. DE C.V.  ', '', '', 1, 0, 2, 'IMPLEMENTOS DE MANUFACTURAS Y SERVICIOS S.A. DE C.V.', '', '', '', 'AVENIDA ENRIQUE PINOCELLI', '9450', '', '', '', 'PUENTE ALTO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 671, 'INTERCORPAC DE MEXICO S DE RL. DE CV.  ', '', '', 1, 0, 2, 'INTERCORPAC DE MEXICO S DE RL. DE CV.', '', '', '', 'HENEQUEN', '10130', '', 'JOSE MATEOS TORRES', '', 'PRADOS DE SALVARCAR', 'JUAREZ', 'JALISCO', '32573'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 672, 'DISTRIBUIDOR DE PRODUCTOS HIDRAULICOS Y NEUMATICOS SA. DE CV  ', '', '', 1, 0, 2, 'DISTRIBUIDOR DE PRODUCTOS HIDRAULICOS Y NEUMATICOS SA. DE CV', '', '', '', 'CARRETERA PANAMERICANA', '9211', '', '', '', 'PUENTE ALTO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 675, 'SEP/DGETI/CETIS 61  ', '', '', 1, 0, 2, 'SEP/DGETI/CETIS 61', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 676, 'HIDROGAS DE CHIHUAHUA S.A. DE C.V.  ', '', '', 1, 0, 2, 'HIDROGAS DE CHIHUAHUA S.A. DE C.V.', '', '', '', 'AV FUENTES MARES', 'KM 1', '', '', '', 'SANTA ROSA', 'CHIHUAHUA', 'JALISCO', '31050'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 677, 'TOMAS ZARAGOZA ITO', 'ZARAGOZA', '', 1, 0, 2, 'TOMAS', 'ZARAGOZA', 'ITO', '', 'CARR. PANAMERICANA', '17', '', 'FRESNOL 1520', 'OSCAR. FRAYLE. VILLITA', 'NUEVO HIPODROMO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 678, 'SAUL DELGADO ', 'DELGADO', '', 1, 0, 2, 'SAUL', 'DELGADO', '', '', 'PALMA PEJIBAGE', '4721', '', '', '', 'PASEO DE LAS PALMAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 679, 'ASESORIA TECNICA DE JUAREZ S.A.  ', '', '', 1, 0, 2, 'ASESORIA TECNICA DE JUAREZ S.A.', '', '', '', 'PANAMERICANA', '10631', '', '', '', '2DO BARRIO', 'AHUMADA', 'JALISCO', '32800'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 720, 'INSTIT. SEG. SERV. SOC. TRAB. EDO.  ', '', '', 1, 0, 2, 'INSTIT. SEG. SERV. SOC. TRAB. EDO.', '', '', '', 'RIO RHIN', '3', '', '', '', 'DELEGACION CUAHUTEMOC', 'MEXICO', 'JALISCO', '6500'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 721, 'ENRIQUE BARRAZA LIMON', 'BARRAZA', '', 1, 0, 2, 'ENRIQUE', 'BARRAZA', 'LIMON', '', 'PITAHAYA', '6445', '', 'HERRERIA PITAHAYA', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 722, 'LA IGLESIA DE JESUCRISTO DE LOS SANTOS DE LOS ULTIMOS DIAS E  ', '', '', 1, 0, 2, 'LA IGLESIA DE JESUCRISTO DE LOS SANTOS DE LOS ULTIMOS DIAS E', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 725, 'JTP INDUSTRIES, SA DE CV  ', '', '', 1, 0, 2, 'JTP INDUSTRIES, SA DE CV', '', '', '', 'AV VICENTE GUERRERO', '3065', '', 'MONTES DE OCA.', '', 'PARTIDO ESCOBEDO CHIHUAHUA', 'JUAREZ', 'JALISCO', '32030'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 727, 'PRODUCTOS ELECTRICOS DIVERSIFICADOS , S.A. DE C.V. YAZAKI ', 'YAZAKI', '', 1, 0, 2, 'PRODUCTOS ELECTRICOS DIVERSIFICADOS , S.A. DE C.V.', 'YAZAKI', '', '', 'DE LA ESTRELLA', '4310', '', '', '', 'PARQUE INDUSTRIAL JUAREZ', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 728, 'SOUTH SHORE JUAREZ S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'SOUTH SHORE JUAREZ S. DE R.L. DE C.V.', '', '', '', 'PARQUE INDUSTRIAL JUAREZ', '3810', '', 'RIVERA LARA', '', 'PARQUE INDUSTRIAL JUAREZ', 'JUAREZ', 'JALISCO', '32630'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 730, 'DANHIL DE MEXICO S.A. DE C.V.  ', '', '', 1, 0, 2, 'DANHIL DE MEXICO S.A. DE C.V.', '', '', '', 'AV. ENRIQUE PINOCELLI', '9340', '', '', '', 'PUENTE ALTO', 'JUAREZ', 'CHIHUAHUA', '32695'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 731, 'FXI DE JUAREZ S.A. DE C.V.  ', '', '', 1, 0, 2, 'FXI DE JUAREZ S.A. DE C.V.', '', '', '', 'AV FULTON', '880', '', '', '', 'PARQUE INDUSTRIAL ANTONIO J', 'JUAREZ', 'JALISCO', '32470'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 733, 'METAL MARKET SA DE CV. INTERCLIMAS DEL NORTE ', 'INTERCLIMAS DEL NORTE', '', 1, 0, 2, 'METAL MARKET SA DE CV.', 'INTERCLIMAS DEL NORTE', '', '', 'SIERRA PEÑA BLANCA', '6715', '', '', '', 'LA CUESTA', 'JUAREZ', 'JALISCO', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 735, 'COLUMBUS INDUSTRIES MEXICO S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'COLUMBUS INDUSTRIES MEXICO S. DE R.L. DE C.V.', '', '', '', 'BLVD. INDEPENDENCIA', '2159', '', 'LIBRE', '', 'PARQUE INDUSTRIAL LAS AMERIC', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 736, 'OPERADORA DE AEROPUERTOS DEL CENTRO NORTE S.A. DE C.V.  ', '', '', 1, 0, 2, 'OPERADORA DE AEROPUERTOS DEL CENTRO NORTE S.A. DE C.V.', '', '', '', 'LAZARO CARDENAS', '2225', '', '', '', 'VALLE OTE NUEVO LEON', 'SAN PEDRO GARZA', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 745, 'PRODUCTOS DE POLIESTIRENO EXPANDIDO SA DE CV PESA ', 'PESA', '', 1, 0, 2, 'PRODUCTOS DE POLIESTIRENO EXPANDIDO SA DE CV', 'PESA', '', '', 'DELICIAS', '6519', '', 'PANAMERICANA', '', 'NUEVO HIPODROMO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 750, 'ECOSERVICIO DEL NORTE S.A. DE C.V.  ', '', '', 1, 0, 2, 'ECOSERVICIO DEL NORTE S.A. DE C.V.', '', '', '', 'MANANTIAL', '1494', '', '', '', 'FUENTES DEL VALLE', 'JUAREZ', 'JALISCO', '32500'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 760, 'JOSE MARIO SERRANO ARZOLA', 'SERRANO', '', 1, 0, 2, 'JOSE MARIO', 'SERRANO', 'ARZOLA', '', 'BLVD. TEOFILO BORUNDA', '8681', '', '', '', 'PLANTA ALTA PARTIDO IGLE', 'JUAREZ', 'JALISCO', '32663'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 761, 'INICIATIVA DEL BRAVO S.A. DE C.V.  ', '', '', 1, 0, 2, 'INICIATIVA DEL BRAVO S.A. DE C.V.', '', '', '', 'BENJAMIN FRANKLIN', '3220', '', 'AV. LINCON', '', 'ZONA PRONAF', 'JUAREZ', 'JALISCO', '32315'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 766, 'ANA MARIA ALDACO ARZATE', 'ALDACO', '', 1, 0, 2, 'ANA MARIA', 'ALDACO', 'ARZATE', '', 'GREGORIO M. SOLIS', '315', '', 'BURRITOS TONY', 'PARQUE BORUNDA', 'PARTIDO ROMERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 768, 'CONCESIONARIA EL ENCIERRO DEL NORTE S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'CONCESIONARIA EL ENCIERRO DEL NORTE S. DE R.L. DE C.V.', '', '', '', 'BLVD GOMEZ MORIN', '7814', '', 'CAMPEROS', '', 'CAMPESTRE', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 769, 'PROMOTORA MISIONES DEL NORTE S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'PROMOTORA MISIONES DEL NORTE S. DE R.L. DE C.V.', '', '', '', 'AV. PASEO DE LA VICTORIA', '4220', '', 'FRENTE A C.C MISIONES', '', 'COL. PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 778, 'SERVICIO PAN AMERICANO DE PROTECCION S.A DE C.V.  ', '', '', 1, 0, 2, 'SERVICIO PAN AMERICANO DE PROTECCION S.A DE C.V.', '', '', '', 'AVE. ADOLFO LOPEZ MATEOS', '1088', 'NORTE', 'HERMANOS ESCOBAR', '', 'FRACC. LA PLAYA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 779, 'ROMERO KUCHLE YOLANDA  ', '', '', 1, 0, 2, 'ROMERO KUCHLE YOLANDA', '', '', '', 'NEPTUNO', '1949', '', '', '', 'SATELITE', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 780, 'DISTRIBUIDORA DE PRODUCTOS AGRICOLAS Y DE CONSUMO  ', '', '', 1, 0, 2, 'DISTRIBUIDORA DE PRODUCTOS AGRICOLAS Y DE CONSUMO', '', '', '', 'JESUS ACEVEDO PORRAS', '406', '', '', '', 'DEPORTISTAS', 'CHIHUAHUA', 'CHIHUAHUA', '31106'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 785, 'SOPORTE ELECTRICO SA DE CV  ', '', '', 1, 0, 2, 'SOPORTE ELECTRICO SA DE CV', '', '', '', 'ADOLFO DE LA HUERTA', '330', '', '', '', 'FRACC. EL COLEGIO', 'JUAREZ', 'JALISCO', '32340'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 790, 'TRANSPORTES INDIO S.A. DE C.V.  ', '', '', 1, 0, 2, 'TRANSPORTES INDIO S.A. DE C.V.', '', '', '', 'COLEGIO MEXICO', '2107', '', '', '', 'LAS MISIONES', 'JUAREZ', 'JALISCO', '32539'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 796, 'PATRICIA MARQUEZ SANCHEZ', 'MARQUEZ', '', 1, 0, 2, 'PATRICIA', 'MARQUEZ', 'SANCHEZ', '', 'BLV MANUEL GOMEZ MORIN', '8431', '', 'TORT. LA MILPA', '', 'PARTIDO SENECU', 'JUAREZ', 'JALISCO', '32470'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 798, 'URIEL VALDEZ VEDOY', 'VALDEZ', '', 1, 0, 2, 'URIEL', 'VALDEZ', 'VEDOY', '', 'ALLENDE', '277', '', 'TORT. YAZMIN', '', 'MORELOS ZARAGOZA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 800, 'OSCAR RICARDO NARVAEZ SOTO', 'NARVAEZ', '', 1, 0, 2, 'OSCAR RICARDO', 'NARVAEZ', 'SOTO', '', 'V GRO', '1642', '', 'CARB.', '2 ABRIL', 'CHIHUAHUA JUAREZ PARTIDO ROM', 'JUAREZ', 'JALISCO', '32030'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 809, 'JUAN JOSE HERNANDEZ MORENO', 'HERNANDEZ', '', 1, 0, 2, 'JUAN JOSE', 'HERNANDEZ', 'MORENO', '', 'ALTOS HORNOS', '5333', '', 'EJ. JUAN GABRIEL', '', 'ACACIAS', 'JUAREZ', 'JALISCO', '32630'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 812, 'CENTRO COMERCIAL COLOSO CHAVEÑA S.A. DE C.V.  ', '', '', 1, 0, 2, 'CENTRO COMERCIAL COLOSO CHAVEÑA S.A. DE C.V.', '', '', '', 'R VELARDE', '243', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 814, 'ALMACENES DISTRIBUIDORES DE LA FRONTERA SA DE CV  ', '', '', 1, 0, 2, 'ALMACENES DISTRIBUIDORES DE LA FRONTERA SA DE CV', '', '', '', 'PLUTARCO ELIAS CALLES', '744', '', '', '', 'PROGRESISTA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 815, 'TIENDAS SORIANA SA DE CV  ', '', '', 1, 0, 2, 'TIENDAS SORIANA SA DE CV', '', '', '', 'ALEJANDRO DE RODAS', '3102', '', '', '', 'CUMBRES 8vo. SECTOR', 'MONTERREY', 'JALISCO', '64610'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 816, 'NUEVA WAL MART DE MEXICO S.DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'NUEVA WAL MART DE MEXICO S.DE R.L. DE C.V.', '', '', '', 'AV. NEXTENGO', '78', '', 'BLVD. ZARAGOZA', '', 'SANTA CRUZ ACAYUCAN', 'AZCAPOTZALCO', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 817, 'TRANSFORMACIONES METALICAS DE JUAREZ SA DE CV.  ', '', '', 1, 0, 2, 'TRANSFORMACIONES METALICAS DE JUAREZ SA DE CV.', '', '', '', 'CAPULIN', '6814', '', 'ZORGO', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 818, 'W. SILVERS DE RL. DE CV.  ', '', '', 1, 0, 2, 'W. SILVERS DE RL. DE CV.', '', '', '', 'AVE. TERCERA', '7038', '', '', '', 'AEROPUERTO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 842, 'BBVA BANCOMER S.A.  ', '', '', 1, 0, 2, 'BBVA BANCOMER S.A.', '', '', '', 'BRASIL', '882', '', 'AVE. UNIVERSIDAD', '', 'HIDALGO', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 858, 'BANDA HERNANDEZ ALMA PATRICIA  ', '', '', 1, 0, 2, 'BANDA HERNANDEZ ALMA PATRICIA', '', '', '', 'GAVIOTAS', '3331 A', '', '', '', 'GRANJAS DE CHAPULTEPEC', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 863, 'LAVADORAS MESA CENTRAL  ', '', '', 1, 0, 2, 'LAVADORAS MESA CENTRAL', '', '', '', 'MEZA CENTRAL', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 866, 'PLASTICOS Y CORRUGADOS DE JUAREZ SA. DE  ', '', '', 1, 0, 2, 'PLASTICOS Y CORRUGADOS DE JUAREZ SA. DE', '', '', '', 'GARAMBULLO', '6185', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 906, 'SERGIO GABRIEL MARTINEZ HERNANDEZ', 'MARTINEZ', '', 1, 0, 2, 'SERGIO GABRIEL', 'MARTINEZ', 'HERNANDEZ', '', 'AV. DE LOS AZTECAS', '7140', '', 'LA MAS BARATA #1', '', 'INDEPENDENCIA 2', 'JUAREZ', 'JALISCO', '32670'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 908, 'RAFAEL CRISTIAN PADILLA GUERRERO', 'PADILLA', '', 1, 0, 2, 'RAFAEL CRISTIAN', 'PADILLA', 'GUERRERO', '', 'MONTECARLO', '8036', '2', 'HOGARAMA', '', 'MONTECARLO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 912, 'ABSA DEL NORTE S.A. DE C.V. ELECTRIC AB SA DE CV ', 'ELECTRIC AB SA DE CV', '', 1, 0, 2, 'ABSA DEL NORTE S.A. DE C.V.', 'ELECTRIC AB SA DE CV', '', '', 'VIALIDAD LOS NOGALES', '3303', '', 'ELECTRICA A-B', '', 'PEDRO DOMINGUEZ', 'CHIHUAHUA', 'JALISCO', '31137'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 923, 'AUTOMATIZACION Y DISEÑO ELECTRONICO DE C  ', '', '', 1, 0, 2, 'AUTOMATIZACION Y DISEÑO ELECTRONICO DE C', '', '', '', 'PEDRO MENESES HOYOS', '6360', 'L2C', 'AYM', '', 'LA CUESTA', 'JUAREZ', 'JALISCO', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 924, 'B & E BOWLING S DE R.L. DE C.V. BOLICHES PETS ', 'BOLICHES PETS', '', 1, 0, 2, 'B & E BOWLING S DE R.L. DE C.V.', 'BOLICHES PETS', '', '', 'PROLONGACION HERMANOS ESCOBAR', '6665', '', 'PROLONGACION HERMANOS ESCOBAR', 'PEREZ SERNA', 'PARQUE INDUSTRIAL OMEGA', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 925, 'MARIO EZIQUIO TORRES GUILLEN', 'TORRES', '', 1, 0, 2, 'MARIO EZIQUIO', 'TORRES', 'GUILLEN', '', 'GABRIEL GAVIRA', '102', '', 'TALLER EL CHAPO', '', 'KILOMETRO 20', 'JUAREZ', 'JALISCO', '32695'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 926, 'INMOBILIARIA SATCHMO, S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'INMOBILIARIA SATCHMO, S. DE R.L. DE C.V.', '', '', '', 'EJE CENTRAL LAZARO CARDENAS', '988', '', '', '', 'NUEVA INDUSTRIAL VALLEJO', 'GUSTAVO A. MADERO', 'JALISCO', '7700'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 995, 'JOAQUIN BERNAL ARMENDARIZ', 'BERNAL', '', 1, 0, 2, 'JOAQUIN', 'BERNAL', 'ARMENDARIZ', '', 'AVE. PANAMERICANA KM 11', '5048', '', 'TORO QUINTACO', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '32390'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1063, 'ACCEL RECINTO FISCALIZADO S.A. DE C.V.  ', '', '', 1, 0, 2, 'ACCEL RECINTO FISCALIZADO S.A. DE C.V.', '', '', '', 'MANUEL J. CLOUTHIER', '1251', '', '', '', 'ND', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1123, 'INSTITUTO DE APOYO AL DESARROLLO TECNOLOGICO CENALTEC ', 'CENALTEC', '', 1, 0, 2, 'INSTITUTO DE APOYO AL DESARROLLO TECNOLOGICO', 'CENALTEC', '', '', 'BARRANCO AZUL', '5961', '', '', '', 'PARQUE IND.AEROPUERTO', 'CHIHUAHUA', 'JALISCO', '32695'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1124, 'GASTRONOMICA PASO DEL NORTE S.A. DE C.V.  ', '', '', 1, 0, 2, 'GASTRONOMICA PASO DEL NORTE S.A. DE C.V.', '', '', '', 'AVENIDA ABRAHAM LINCONN', '1002', '', '', '', 'LA PLAYA', 'JUAREZ', 'JALISCO', '32317'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1125, 'RAFAEL HOLGUIN MONARREZ', 'HOLGUIN', '', 1, 0, 2, 'RAFAEL', 'HOLGUIN', 'MONARREZ', '', 'JOSE  CONTRERAS AGUILAR', '3105', '78', '', '', 'CARLOS CASTILLO PERAZA (TIERRA NUEVA 6)', 'JUAREZ', 'JALISCO', '32575'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1127, 'UNIVERSIDAD PEDAGOGICA NACIONAL DEL ESTADO DE CHIHUAHUA  ', '', '', 1, 0, 2, 'UNIVERSIDAD PEDAGOGICA NACIONAL DEL ESTADO DE CHIHUAHUA', '', '', '', '2A', '1400', '', '', '', 'ZONA CENTRO', 'JUAREZ', 'JALISCO', '39000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1128, 'GRUPO FRUDI SA DE CV.  ', '', '', 1, 0, 2, 'GRUPO FRUDI SA DE CV.', '', '', '', 'MARIANO JIMENEZ', '1438', '', '', '', 'SALVACAR', 'JUAREZ', 'JALISCO', '32599'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1129, 'SERVICIO POSTAL MEXICANO  ', '', '', 1, 0, 2, 'SERVICIO POSTAL MEXICANO', '', '', '', 'TABUCA', '1', '', '', '', 'CENTRODE LA CIUDAD DE MEXICO', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1131, 'ENRIQUE CARREON ', 'CARREON', '', 1, 0, 2, 'ENRIQUE', 'CARREON', '', '', 'CALZADA DEL RIO', '8908', '8', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1139, 'MARINA BENAVIDES MORALES', 'BENAVIDES', '', 1, 0, 2, 'MARINA', 'BENAVIDES', 'MORALES', '', 'HIMNO NACIONAL', '5427', '', 'TORT FLOR DE MAIZ', '', 'SAN FELIPE DEL REAL', 'JUAREZ', 'JALISCO', '32159'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1140, 'CARLOS GONZALEZ ', 'GONZALEZ', '', 1, 0, 2, 'CARLOS', 'GONZALEZ', '', '', '18 DE MARZO', '3305', '4', '', 'IVAN VIRAMONTES', 'LA JOYA', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1144, 'FUNDIDORA URECA , S.A. DE C.V.  ', '', '', 1, 0, 2, 'FUNDIDORA URECA , S.A. DE C.V.', '', '', '', 'MIXTECOS', '2378', '', 'OTOMIES', '', 'AZTECA', 'JUAREZ', 'JALISCO', '32280'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1145, 'MARTINEZ SAENZ JESSICA ISABEL ISLA ZAPATA JAIME ENRIQUE', 'ISLA ZAPATA', '', 1, 0, 2, 'MARTINEZ SAENZ JESSICA ISABEL', 'ISLA ZAPATA', 'JAIME ENRIQUE', '', 'ISLAS BALEARES', '2805', '', 'LA MAS BARATA # 5 ( ZAPATA)', 'JAIME ENRIQUEZ HERNANDEZ', 'GUADALAJARA DERECHA', 'JUAREZ', 'JALISCO', '32220'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1146, 'VERGELES ETERNOS SA DE CV.  ', '', '', 1, 0, 2, 'VERGELES ETERNOS SA DE CV.', '', '', '', 'FRESNEL', '9305', '', '', '', 'PARTIDO SENECU', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1150, 'CENTRO COMERCIAL MISIONES  ', '', '', 1, 0, 2, 'CENTRO COMERCIAL MISIONES', '', '', '', 'TEOFILO BORUNDA', '8681', '', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1151, 'INVENTSE S DE RL DE CV  ', '', '', 1, 0, 2, 'INVENTSE S DE RL DE CV', '', '', '', 'AV. DEL VALLE', '1578', '', '', '', 'SALVACAR', 'JUAREZ', 'CHIHUAHUA', '32580'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1153, 'PR ENTERTAINMENT DEL NORTE SA DE CV RAUL RODRIGUEZ ', 'RAUL RODRIGUEZ', '', 1, 0, 2, 'PR ENTERTAINMENT DEL NORTE SA DE CV', 'RAUL RODRIGUEZ', '', '', 'AV. GOMEZ MORIN', '7891', '', 'CASINO GOLDEN PREASURE', '', 'CAMPESTRE', 'JUAREZ', 'CHIHUAHUA', '32460'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1155, 'CONSTRUCTORA PASO DEL NORTE  ', '', '', 1, 0, 2, 'CONSTRUCTORA PASO DEL NORTE', '', '', '', 'PASEO DE LAS FLORES', '221', '', 'PASEO DE LA HUERTA', 'PASEO DEL BOSQUE SUR', 'SAN ANTONIO', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1157, 'COMITE DE APOYO PUERTO FRONTERIZO ZARAGOZA YSLETA  ', '', '', 1, 0, 2, 'COMITE DE APOYO PUERTO FRONTERIZO ZARAGOZA YSLETA', '', '', '', 'MALECON', 'SN', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', '32000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1160, 'OPERADORA MUNICIPAL DE ESTACIONAMIENTO DE JUAREZ  ', '', '', 1, 0, 2, 'OPERADORA MUNICIPAL DE ESTACIONAMIENTO DE JUAREZ', '', '', '', 'GENERAL RIVAS GUILLEN', '659 NORTE', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', '32000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1162, 'SARACHO JUAREZ S.A. DE C.V.  ', '', '', 1, 0, 2, 'SARACHO JUAREZ S.A. DE C.V.', '', '', '', 'PASEO TRIUNFO DE LA REPUBLICA', '2600 OTE', '', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1166, 'COMITE DE APOYO PUERTO FRONTERIZO SAN GERONIMO SAN SANTA TERESA ', 'SANTA TERESA', '', 1, 0, 2, 'COMITE DE APOYO PUERTO FRONTERIZO SAN GERONIMO SAN', 'SANTA TERESA', '', '', 'MALECON', 'SN', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1167, 'JARDINES ETERNOS S.A. DE C.V.  ', '', '', 1, 0, 2, 'JARDINES ETERNOS S.A. DE C.V.', '', '', '', 'NEPTUNO', '3159', '', '', '', 'SATELITE', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1168, 'MUÑOZ SALCIDO MA MALLELA  ', '', '', 1, 0, 2, 'MUÑOZ SALCIDO MA MALLELA', '', '', '', 'BLVD PROL TEOFILO BORUNDA', '8740', '', 'AV. WATERFILL', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '32663'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1169, 'NEGOCIOS ESTEPA  ', '', '', 1, 0, 2, 'NEGOCIOS ESTEPA', '', '', '', 'AVE TECNOLOGICO', '1770', '', 'PEDRO ROSALES DE LEON', '', 'FUENTES DEL VALLE', 'JUAREZ', 'JALISCO', '32500'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1170, 'TOMAS MORALES RUIZ LAURA PONCE ', 'LAURA PONCE', '', 1, 0, 2, 'TOMAS MORALES RUIZ', 'LAURA PONCE', '', '', 'CARLOS AMAYA', '7330', '242', 'CARNITAS JUAREZ MCDO ABASTOS', 'AERONAUTICA', 'AZTECA', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1172, 'CARDENAL EXPRESS , S.A. DE  C.V.  ', '', '', 1, 0, 2, 'CARDENAL EXPRESS , S.A. DE  C.V.', '', '', '', 'BLVD. TOMAS FERNANDEZ', '8255', '9A', 'ANTONIO J. BERMUDEZ', 'MANANTIAL', 'CAMPESTRE', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1173, 'UNIVERSIDAD TECNOLOGICA PASO DEL NORTE  ', '', '', 1, 0, 2, 'UNIVERSIDAD TECNOLOGICA PASO DEL NORTE', '', '', '', 'PEZ LUCIO', '10526', '', '', '', 'PUERTO DE ANAPRA', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1174, 'ABEL REFUGIO BERNAL LARA', 'BERNAL', '', 1, 0, 2, 'ABEL REFUGIO', 'BERNAL', 'LARA', '', 'INTERNACIONAL WATERFILL', '219', '', 'TORO BRONCO', '', 'RIO BRAVO', 'JUAREZ', 'JALISCO', '32550'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1178, 'MANUEL JESUS ESTRADA HOUSTON', 'ESTRADA', '', 1, 0, 2, 'MANUEL JESUS', 'ESTRADA', 'HOUSTON', '', 'VILLA DE LAS ROSAS', '8545', '12', '', '', 'LAS QUINTAS', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1181, 'KAREM SOFIA CASTRO BURCIAGA', 'CASTRO', '', 1, 0, 2, 'KAREM SOFIA', 'CASTRO', 'BURCIAGA', '', 'PORTALES', '802', '', 'NOM-NOM', '', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1182, 'OPERADORA DE DIVERSION CONTINUA SA DE CV  ', '', '', 1, 0, 2, 'OPERADORA DE DIVERSION CONTINUA SA DE CV', '', '', '', 'DE LOS PORTALES', '802', '', '', '', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1183, 'PRODUCTOS Y SERVICIOS RESTAURANTEROS GRUPO CINCO S PAN & OLI ', 'PAN & OLI', '', 1, 0, 2, 'PRODUCTOS Y SERVICIOS RESTAURANTEROS GRUPO CINCO S', 'PAN & OLI', '', '', 'EUGENIO GARZA SADA', '3820', '7', '', '', 'CONTRY', 'NUEVO LEON', 'JALISCO', '64860'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1184, 'ARMANDO VILLAR RODRIGUEZ', 'VILLAR', '', 1, 0, 2, 'ARMANDO', 'VILLAR', 'RODRIGUEZ', '', 'PORTALES', '802', '6', 'WING STOP', '', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1185, 'SERVICIOS ALIMENTICIOS LA JUAREZ S DE RL DE CV  ', '', '', 1, 0, 2, 'SERVICIOS ALIMENTICIOS LA JUAREZ S DE RL DE CV', '', '', '', 'BELISARIO DOMINGUEZ', '2005', 'B', '', '', 'MONTERREY', 'JUAREZ', 'JALISCO', '32070'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1187, 'COMITE DE APOYO PUERTO FRONTERIZO CORDOVA DE LAS A  ', '', '', 1, 0, 2, 'COMITE DE APOYO PUERTO FRONTERIZO CORDOVA DE LAS A', '', '', '', 'AVE. MALECON', 'SN', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1189, 'CORPORATIVO EMPRESARIAL LOPEZ SA DE CV  ', '', '', 1, 0, 2, 'CORPORATIVO EMPRESARIAL LOPEZ SA DE CV', '', '', '', 'AVE. JUAREZ', '219', '', '', '', 'CENTRO', 'GUADALUPE', 'JALISCO', '32740'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1190, 'CASTRO VAZQUEZ ZORAIDA  ', '', '', 1, 0, 2, 'CASTRO VAZQUEZ ZORAIDA', '', '', '', 'DR. PORFIRIO PARRA', '215', '', '', '', 'CENTRO', 'GUADALUPE', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1196, 'FLEXTRONICS AUTOMOTIVE DE JUAREZ S.A. DE C.V.  ', '', '', 1, 0, 2, 'FLEXTRONICS AUTOMOTIVE DE JUAREZ S.A. DE C.V.', '', '', '', 'OMEGA', '1825', '', '', '', 'PARQUE INDUSTRIAL OMEGA', 'JUAREZ', 'CHIHUAHUA', '32410'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1197, 'CESAR LEOPOLDO GARCIA TARIN ', 'GARCIA TARIN', '', 1, 0, 2, 'CESAR LEOPOLDO', 'GARCIA TARIN', '', '', 'CIRCUITO ROBLE', '1019', '', '', '', 'HACIENDA DEL NOGAL', 'JUAREZ', 'CHIHUAHUA', '32400'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1199, 'INSTITUTO MUNICIPAL DEL DEPORTE Y CULTURA FISICA D  ', '', '', 1, 0, 2, 'INSTITUTO MUNICIPAL DEL DEPORTE Y CULTURA FISICA D', '', '', '', 'AV. DE LAS AMERICAS', '350', 'SUR', '', '', 'PARTIDO ESCOBEDO', 'JUAREZ', 'CHIHUAHUA', '32330'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1201, 'DISEÑO Y CREACIONES EN EVENTOS SA DE CV.  ', '', '', 1, 0, 2, 'DISEÑO Y CREACIONES EN EVENTOS SA DE CV.', '', '', '', 'DE LOS PORTALES', '802', 'L18', '', '', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32530'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1202, 'TAQUERIA LA NUMERO 4 S DE RL DE CV  ', '', '', 1, 0, 2, 'TAQUERIA LA NUMERO 4 S DE RL DE CV', '', '', '', 'DE LOS PORTALES', '802', 'L7 L8', 'BLVD TOMAS FERNANDEZ', 'MORO', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1204, 'TRANSPORTE DE PERSONAL JOSELYN S.A DE C.V  ', '', '', 1, 0, 2, 'TRANSPORTE DE PERSONAL JOSELYN S.A DE C.V', '', '', '', 'QUICHES', '6727', '', '', '', 'AZTECA', 'JUAREZ', 'CHIHUAHUA', '32280'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1206, 'BEBIDAS MUNDIALES S. DE R.L.DE C.V.  ', '', '', 1, 0, 2, 'BEBIDAS MUNDIALES S. DE R.L.DE C.V.', '', '', '', 'AV. ALFONSO REYES', '3001', '', '', '', 'REGINA', 'MONTERREY', 'NUEVO LEON', '64290'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1208, 'REALIM DE MEXICO SC DE RL  ', '', '', 1, 0, 2, 'REALIM DE MEXICO SC DE RL', '', '', '', 'BENITO JUAREZ', '508', '', '', '', 'CENTRO', 'GUADALUPE', 'MEXICO', '32744'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1209, 'NICCO DE MEXICO S.A. DE C.V.  ', '', '', 1, 0, 2, 'NICCO DE MEXICO S.A. DE C.V.', '', '', '', 'CARR. JUAREZ PORVENIR', '3194', '', '', '', 'CENTRO', 'LOMA BLANCA', 'MEXICO', '32508'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1211, 'COMERCIALIZADORA Y AUTOSERVICIO GONZALEZ ZAPATA RAFAEL ', 'GONZALEZ ZAPATA RAFAEL', '', 1, 0, 2, 'COMERCIALIZADORA Y AUTOSERVICIO', 'GONZALEZ ZAPATA RAFAEL', '', '', 'SANTA TERESA', '1131', '', '', '', 'MAESTROS ESTATALES', 'JUAREZ', 'CHIHUAHUA', '32180'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1215, 'BEATEC, S DE RL DE CV PAK SAE GEUN ', 'PAK SAE GEUN', '', 1, 0, 2, 'BEATEC, S DE RL DE CV', 'PAK SAE GEUN', '', '', 'LA MURALLA ORIENTE', '1020', '', '', '', 'LA MURALLA', 'JUAREZ', 'CHIHUAHUA', '32600'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1216, 'SILVER GROUP DE JUAREZ SA DE CV  ', '', '', 1, 0, 2, 'SILVER GROUP DE JUAREZ SA DE CV', '', '', '', 'C. COSTA DE MARFIL', '9528', '', 'CASINO GRAN DUNAS', '', 'QUINTA DE VERSALLES', 'JUAREZ', 'JALISCO', '31313'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1217, 'SISTEMAS INDUSTRIALIZADOS S DE RL BARRIGAS STA TERESA ', 'BARRIGAS STA TERESA', '', 1, 0, 2, 'SISTEMAS INDUSTRIALIZADOS S DE RL', 'BARRIGAS STA TERESA', '', '', 'TOMAS FERNANDEZ', '8592', '4', '', '', '2DO BARRIO', 'AHUMADA', 'CHIHUAHUA', '32460'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1218, 'MADAGOEN S DE RL DE CV RESERVA 21 ', 'RESERVA 21', '', 1, 0, 2, 'MADAGOEN S DE RL DE CV', 'RESERVA 21', '', '', 'PORTALES', '802', '8', '', '', 'SAN MARCOS', 'JUAREZ', 'JALISCO', '32409'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1219, 'ALIMENTOS ORIENTALES SHINTO S. DE R.L. DE C.V.  ', '', '', 1, 0, 2, 'ALIMENTOS ORIENTALES SHINTO S. DE R.L. DE C.V.', '', '', '', 'PORTALES', '802', '2 Y 3', '', '', 'PARTIDO MANUEL DOBLADO', 'JUAREZ', 'CHIHUAHUA', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1220, 'SERVICIOS DE CATERING SAN LUIS CATERING ', 'CATERING', '', 1, 0, 2, 'SERVICIOS DE CATERING SAN LUIS', 'CATERING', '', '', 'INDUSTRIAL 5', 'BODEGA G38', 'G39', '', '', 'AEROPUERTO', 'CHIHUAHUA', 'CHIHUAHUA', '31384'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1221, 'MOLINERA DE MEXICO, S.A. DE C.V.  ', '', '', 1, 0, 2, 'MOLINERA DE MEXICO, S.A. DE C.V.', '', '', '', 'EJE VIAL JUAN GABRIEL', '7891', '', '', 'NO HACERLE NOTA DE DESC', 'JARUDO DEL NORTE', 'JUAREZ', 'CHIHUAHUA', '32652'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1222, 'INDUSTRIAL INTERNATIONAL SERVICES, SA DE CV  ', '', '', 1, 0, 2, 'INDUSTRIAL INTERNATIONAL SERVICES, SA DE CV', '', '', '', 'AV. ROSA MA. Y FUENTES', '7451', '', '', '', 'PARQUE INDUSTRIAL LOS FUENTES', 'JUAREZ', 'CHIHUAHUA', '32320'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1223, 'BERNAL LARA ANGELICA PATRICIA TORO EJERCITO ', 'TORO EJERCITO', '', 1, 0, 2, 'BERNAL LARA ANGELICA PATRICIA', 'TORO EJERCITO', '', '', 'SIERRA SAN CARLOS', '5686', '', '', '', 'LA CUESTA', 'JUAREZ', 'CHIHUAHUA', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1224, 'DEPOSITO JONNY  ', '', '', 1, 0, 2, 'DEPOSITO JONNY', '', '', '', 'HIMNO NACIONAL', '8797', '', '', '', 'SAN FELIPE DEL REAL', 'JUAREZ', 'CHIHUAHUA', '32177'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1225, 'BERNAL PEREZ JOSE JUAN ', 'JOSE JUAN', '', 1, 0, 2, 'BERNAL PEREZ', 'JOSE JUAN', '', '', 'BLVD. OSCAR FLORES', '5105', '', '', '', 'LA CUESTA', 'JUAREZ', 'CHIHUAHUA', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1227, 'MAQUILADOS FRONTERIZOS DEL NORTE DIPRENTA ', 'DIPRENTA', '', 1, 0, 2, 'MAQUILADOS FRONTERIZOS DEL NORTE', 'DIPRENTA', '', '', 'JUAN KEPLER', '6776', '', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'CHIHUAHUA', '32663'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1229, 'RESTAURANTES HISPANOAMERICANOS DEL NORTE SABOR AMOR ', 'SABOR AMOR', '', 1, 0, 2, 'RESTAURANTES HISPANOAMERICANOS DEL NORTE', 'SABOR AMOR', '', '', 'AV. DE LOS PORTALES', '802', '', '', '', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1230, 'GRUPO INSTITUCIONAL Y COMERCIAL MEXICO  ', '', '', 1, 0, 2, 'GRUPO INSTITUCIONAL Y COMERCIAL MEXICO', '', '', '', 'PASEO DE LOS CANARIOS', '7731', '8B', '', '', 'PASEO DEL ALBA', 'JUAREZ', 'CHIHUAHUA', '32696'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1232, 'COMPAÑIA IMPORTADORA DE GAS Y PETROLEO DEL GOLFO TORRE ', 'TORRE', '', 1, 0, 2, 'COMPAÑIA IMPORTADORA DE GAS Y PETROLEO DEL GOLFO', 'TORRE', '', '', 'RODRIGUEZ GALLARDO', '807', '', 'PEDRO DE ARIZAGA', '', 'SAN FELIPE II', 'CHIHUAHUA', 'CHIHUAHUA', '31203'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1233, 'PAVIMENTOS Y AGREGADOS DEL DESIERTO CONSTRUCTORA NIRVANA ', 'CONSTRUCTORA NIRVANA', '', 1, 0, 2, 'PAVIMENTOS Y AGREGADOS DEL DESIERTO', 'CONSTRUCTORA NIRVANA', '', '', 'AVENIDA VICENTE LOMBARDO TOLEDANO', 'SN', '', '', '', 'LADRILLEROS', 'CHIHUAHUA', 'CHIHUAHUA', '31375'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1235, 'PROCESOS LOGISTICOS OUTSOURCING, SA DE CV  ', '', '', 1, 0, 2, 'PROCESOS LOGISTICOS OUTSOURCING, SA DE CV', '', '', '', 'AVE. CUAUHTEMOC', '2800', 'PISO 6', '', '', 'UNIDAD CUAUHTEMOC', 'CHIHUAHUA', 'CHIHUAHUA', '31470'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1236, 'SOPORTE CON SERVICIOS Y SUMINISTROS  ', '', '', 1, 0, 2, 'SOPORTE CON SERVICIOS Y SUMINISTROS', '', '', '', 'LIBRAMIENTO REGIONAL', '8204', '', '', '', 'CAMPESTRE ARBOLADA', 'JUAREZ', 'CHIHUAHUA', '32409'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1237, 'OPERADORA ENNO, S. DE RL. DE C.V  ', '', '', 1, 0, 2, 'OPERADORA ENNO, S. DE RL. DE C.V', '', '', '', 'PORTALES', '802', '12', 'RICARDO ENRIQUE YU TRUEBA', 'COCINA ELENA', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1238, 'ANDRES SALGADO SANCHEZ / FELISA ', '/ FELISA', '', 1, 0, 2, 'ANDRES SALGADO SANCHEZ', '/ FELISA', '', '', 'PORTALES', '802', '', '', '', 'PARTIDO DOBLADO', 'JUAREZ', 'CHIHUAHUA', '32424'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1239, 'BARNHART TAYLOR MX, S.A. DE C.V.  ', '', '', 1, 0, 2, 'BARNHART TAYLOR MX, S.A. DE C.V.', '', '', '', 'LUIS L. LEON', '9626', '', '', '', 'PARQUE INDUSTRIAL ANTONIO J. BERMUDEZ', 'JUAREZ', 'CHIHUAHUA', '32470'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1240, 'APLICADORES MEXICANOS  ', '', '', 1, 0, 2, 'APLICADORES MEXICANOS', '', '', '', 'MAGNETO', '951', '', '', '', 'PARQUE INDUSTRIAL GEMA', 'JUAREZ', 'CHIHUAHUA', '32648'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1241, 'RAUL BARRAZA ITO', 'BARRAZA', '', 1, 0, 2, 'RAUL', 'BARRAZA', 'ITO', '', 'AV. TECNOLOGICO', '900', 'A', '', '', 'CRUCERO', 'CD JUAREZ', 'CHIHUAHUA', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1243, 'GUILLERMO MARTINEZ PEREZ  ', '', '', 1, 0, 2, 'GUILLERMO MARTINEZ PEREZ', '', '', '', 'JARDINES DE MEDIN', '3614', '', 'EXPORT DELICIAS', '', 'JARDINES RESIDENCIAL', 'JUAREZ', 'CHIHUAHUA', '32618'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 1244, 'JORGE MARTINEZ PEREZ  ', '', '', 1, 0, 2, 'JORGE MARTINEZ PEREZ', '', '', '', 'ROSALEDA PTE.', '2635', '', 'EXPORT CAMARGO', '', 'BUGAMBILIAS', 'JUAREZ', 'CHIHUAHUA', '32534'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3023, 'ASOC. DE PADRES DE P  ', '', '', 1, 0, 2, 'ASOC. DE PADRES DE P', '', '', '', 'CARRETERA PANAMERICANA', 'KM. 20', '', '', '', 'FRACC. PUENTE ALTO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3034, 'AGUIRRE TREJO NEREID  ', '', '', 1, 0, 2, 'AGUIRRE TREJO NEREID', '', '', '', 'DIV. C/PEMEX', '7833', '', '', '', 'FIDEL VELAZQUEZ', 'JUAREZ', 'JALISCO', '32217'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3036, 'SERV INDUSTRIAL,S.A.  ', '', '', 1, 0, 2, 'SERV INDUSTRIAL,S.A.', '', '', '', 'CALLE CUARTA', '1218', '', '', '', 'COL. TORRES DEL PRI', 'JUAREZ', 'JALISCO', '32574'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3038, 'DAVILA DOZAL ARTURO  ', '', '', 1, 0, 2, 'DAVILA DOZAL ARTURO', '', '', '', 'ESTACION BUSTILLOS', '11620', '', '', '', 'FRACC. JARDINES DE SATELITE', 'ND', 'JALISCO', '32543'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3044, 'GRUPO AMEX S.A. DE C  ', '', '', 1, 0, 2, 'GRUPO AMEX S.A. DE C', '', '', '', 'AV. INTERNACIONAL', '208', '', '', '', 'WATERFILL RIO BRAVO', 'JUAREZ', 'JALISCO', '32550'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3046, 'REYNOSO CHAVEZ MARIA  ', '', '', 1, 0, 2, 'REYNOSO CHAVEZ MARIA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3050, 'RODRIGUEZ REYES ROBE  ', '', '', 1, 0, 2, 'RODRIGUEZ REYES ROBE', '', '', '', 'GRAL. GUILLERMO CHAVEZ', '7857', 'SUR', '', '', 'REVOLUCION MEXICANA', 'JUAREZ', 'JALISCO', '32670'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3058, 'AVILA ESPINOZA MA.GU  ', '', '', 1, 0, 2, 'AVILA ESPINOZA MA.GU', '', '', '', 'BOLIVIA NORTE', '178', '', '', '', 'PARTIDO ROMERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3063, 'ISSA INDUSTRIAL,S.DE  ', '', '', 1, 0, 2, 'ISSA INDUSTRIAL,S.DE', '', '', '', 'CALLE INDUSTRIAL UNO', 'SN', '', '', '', 'AEROPUERTO', 'CHIHUAHUA', 'JALISCO', '31390'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3077, 'ALMACENES DISTRIBUID  ', '', '', 1, 0, 2, 'ALMACENES DISTRIBUID', '', '', '', 'C. PLUTARCO ELIAS CALLES', '744', '', '', '', 'COL. PROGRESISTA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3082, 'AGUIRRE TREJO ABELAR  ', '', '', 1, 0, 2, 'AGUIRRE TREJO ABELAR', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3083, 'AGUIRRE TREJO JAVIER  ', '', '', 1, 0, 2, 'AGUIRRE TREJO JAVIER', '', '', '', 'MERCADO DE ABASTOS', '44644', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3084, 'ZUBIA ALCANTAR GERAR  ', '', '', 1, 0, 2, 'ZUBIA ALCANTAR GERAR', '', '', '', 'C.CANANEA', '3927', '', '', '', 'FRONTERIZA BAJA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3091, 'AGUIRRE TREJO FRANCI  ', '', '', 1, 0, 2, 'AGUIRRE TREJO FRANCI', '', '', '', 'INGENIERO ANGEL MOLINA', '3866', '', '', '', 'COL. GUADALAJARA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3098, 'FLORES CHAVEZ ROBERT  ', '', '', 1, 0, 2, 'FLORES CHAVEZ ROBERT', '', '', '', 'AV. HIDALGO', '2590', '', '', '', 'FRACC. SAN ANTONIO', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3099, 'SUPER AUTOS GOFY SA  ', '', '', 1, 0, 2, 'SUPER AUTOS GOFY SA', '', '', '', 'MANUEL J. CLOUTHIER', '7149', '', '', '', 'FRACC. DEL REAL', 'ND', 'JALISCO', '32660'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3108, 'AGUIRRE TREJO ENRIQU  ', '', '', 1, 0, 2, 'AGUIRRE TREJO ENRIQU', '', '', '', 'C.NAVOJOA', '3509', '', '', '', 'FRONTERIZA BAJA', 'JUAREZ', 'JALISCO', '32220'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3109, 'INDUSTRIALIZADORA DE  ', '', '', 1, 0, 2, 'INDUSTRIALIZADORA DE', '', '', '', 'ETHEL CUERVO HUERTA', '7620', '', '', '', 'COL. INDEPENDENCIA No. 2', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3124, 'FBF INDUSTRIAL SA DE  ', '', '', 1, 0, 2, 'FBF INDUSTRIAL SA DE', '', '', '', 'JOSEFINA', '6627', '', '', '', 'LOMAS DEL REY', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3125, 'IMPERMEABILIZANTES Y  ', '', '', 1, 0, 2, 'IMPERMEABILIZANTES Y', '', '', '', 'AV. SIMONA BARBA', '5344', '', '', '', 'FRACC. LOS BOSQUES', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3138, 'CONSTRUCTORA ANGLO,  ', '', '', 1, 0, 2, 'CONSTRUCTORA ANGLO,', '', '', '', 'AV. TEOFILO BORUNDA', '7751', '301', '', '', 'FRACC. BOSQUES DEL SOL', 'JUAREZ', 'JALISCO', '32616'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3154, 'DESARROLLADORA DE CA  ', '', '', 1, 0, 2, 'DESARROLLADORA DE CA', '', '', '', 'BLVD. ALFONSO ZARAGOZA MAYTORENA', '2204', '', '', '', 'FRACC. BONANZA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3155, 'CONSTRUCTORA VIMO SA  ', '', '', 1, 0, 2, 'CONSTRUCTORA VIMO SA', '', '', '', 'COLOMBIA', '738', '', '', '', 'ENTRE 18 DE MARZO Y 2 DE ABR', 'ND', 'JALISCO', '32330'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3158, 'ABASTECEDORA FRONTER  ', '', '', 1, 0, 2, 'ABASTECEDORA FRONTER', '', '', '', 'EJE VIAL JUAN GABRIEL', '3070', 'A', '', '', 'SOL DE MAYO', 'JUAREZ', 'JALISCO', '32620'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3169, 'MERCADO Y BODEGA DE  ', '', '', 1, 0, 2, 'MERCADO Y BODEGA DE', '', '', '', 'AV. EJERCITO NACIONAL', '5225', '', '', '', 'FRACC. JARDINES DE SAN JOSE', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3171, 'ROMERO DEL RIO MANUE  ', '', '', 1, 0, 2, 'ROMERO DEL RIO MANUE', '', '', '', 'PARQUE REAL', '8267', '', '', '', 'FRACC LOS PARQUES', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3174, 'LACTEOS DON CHENTE,  ', '', '', 1, 0, 2, 'LACTEOS DON CHENTE,', '', '', '', 'CEILAN', '6310', '', '', '', 'AMPLIACION AEROPUERTO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3175, 'ACEITES,GRASAS Y DER  ', '', '', 1, 0, 2, 'ACEITES,GRASAS Y DER', '', '', '', 'AV.VALLARTA', '5106', '', '', '', 'JUAN M VALLARTA', 'ZAPOPAN', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3177, 'INFRA, S.A DE C.V  ', '', '', 1, 0, 2, 'INFRA, S.A DE C.V', '', '', '', 'EJE VIAL JUAN GABRIEL', '7074', '', '', '', 'PARQUE INDUSTRIAL GEMA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3182, 'REYNA VIDAL PANTALEO  ', '', '', 1, 0, 2, 'REYNA VIDAL PANTALEO', '', '', '', 'NEPTUNO', '1789', '', '', '', 'COL. SATELITE', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3207, 'REFACCIONARIA VALATI  ', '', '', 1, 0, 2, 'REFACCIONARIA VALATI', '', '', '', 'PASEO TRIUNFO DE LA REPUBLICA', '935', '', '', '', 'DEL FUTURO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3209, 'CADENA COMERCIAL OXX  ', '', '', 1, 0, 2, 'CADENA COMERCIAL OXX', '', '', '', 'C. NICOLAS GOGOL', '11363', '', '', '', 'COMPLEJO INDUSTRIAL CHIHUAHU', 'CHIHUAHUA', 'JALISCO', '31136'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3220, 'POLIMEROS, ADHESIVOS  ', '', '', 1, 0, 2, 'POLIMEROS, ADHESIVOS', '', '', '', 'JOSE ELEUTERIO GONZALEZ', '900', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3252, 'HOME DEPOT MEXICO S  ', '', '', 1, 0, 2, 'HOME DEPOT MEXICO S', '', '', '', 'RICARDO MARGAIN ZOZAYA', '605', '', '', '', 'SANTA ENGRACIA', 'GARCIA', 'JALISCO', '66267'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3295, 'UNION DE CONCESIONAR  ', '', '', 1, 0, 2, 'UNION DE CONCESIONAR', '', '', '', 'INOCENTE OCHOA', '4444', '', '', '', 'CENTRO', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3299, 'MORALES VARGAS SUSAN  ', '', '', 1, 0, 2, 'MORALES VARGAS SUSAN', '', '', '', 'C. FILODENDRO', '5710', '', '', '', 'INFO. ANGEL TRIAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3300, 'RENOVA COMERCIAL SA  ', '', '', 1, 0, 2, 'RENOVA COMERCIAL SA', '', '', '', 'AGUIRRE LAREDO', '6605', '', '', '', 'PARTIDO LA FUENTE', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3302, 'GARCIA ALVELAIS GABR  ', '', '', 1, 0, 2, 'GARCIA ALVELAIS GABR', '', '', '', 'LOMBARDO TOLEDANO', '1722', '', '', '', 'INDUSTRIAL', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3303, 'DISTRIBUIDORA CARACO  ', '', '', 1, 0, 2, 'DISTRIBUIDORA CARACO', '', '', '', 'EJE VIAL JUAN GABRIEL', '4240', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3304, 'OSORNO EXPRESS  ', '', '', 1, 0, 2, 'OSORNO EXPRESS', '', '', '', 'AMATITLAN', '6553', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3306, 'ALONSO JAIME URIEL  ', '', '', 1, 0, 2, 'ALONSO JAIME URIEL', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3307, 'MIRAMONTES SOTO LEON  ', '', '', 1, 0, 2, 'MIRAMONTES SOTO LEON', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3308, 'PRECISION MOLDINGS D  ', '', '', 1, 0, 2, 'PRECISION MOLDINGS D', '', '', '', 'EJE VIAL JUAN GABRIEL', '4417', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3310, 'SANIDAD ECOLOGICA DE  ', '', '', 1, 0, 2, 'SANIDAD ECOLOGICA DE', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3311, 'DISTRIBUIDORA PASO D  ', '', '', 1, 0, 2, 'DISTRIBUIDORA PASO D', '', '', '', 'TARASCOS ESQ. NAHOAS', '5955', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3312, 'ELECTRO ACABADOS Y S  ', '', '', 1, 0, 2, 'ELECTRO ACABADOS Y S', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3313, 'GAMBOA MINJAREZ OSCA  ', '', '', 1, 0, 2, 'GAMBOA MINJAREZ OSCA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3314, 'REYES HERNANDEZ YOLA  ', '', '', 1, 0, 2, 'REYES HERNANDEZ YOLA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3315, 'PEDROZA ORTIZ LORENZ  ', '', '', 1, 0, 2, 'PEDROZA ORTIZ LORENZ', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3317, 'LOPEZ MONARREZ FRANC  ', '', '', 1, 0, 2, 'LOPEZ MONARREZ FRANC', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3318, 'NAVARRETE DOMINGUEZ  ', '', '', 1, 0, 2, 'NAVARRETE DOMINGUEZ', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3319, 'PEREZ RUELAS LUIS FE  ', '', '', 1, 0, 2, 'PEREZ RUELAS LUIS FE', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3320, 'OLIVARES GEORGINA BE  ', '', '', 1, 0, 2, 'OLIVARES GEORGINA BE', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3321, 'CARDIEL DOMINGUEZ JU  ', '', '', 1, 0, 2, 'CARDIEL DOMINGUEZ JU', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3322, 'ALMACENES ESPINO  ', '', '', 1, 0, 2, 'ALMACENES ESPINO', '', '', '', 'TOTONACAS', '5834', '', '', '', 'AZTECA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3323, 'ORTIZ ARECHIGA MARIA  ', '', '', 1, 0, 2, 'ORTIZ ARECHIGA MARIA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3324, 'GARCIA LUNA ARMANDO  ', '', '', 1, 0, 2, 'GARCIA LUNA ARMANDO', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3325, 'PROCESOS GALVANIZADA  ', '', '', 1, 0, 2, 'PROCESOS GALVANIZADA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3326, 'AZTECA BLOCKS CONCRE  ', '', '', 1, 0, 2, 'AZTECA BLOCKS CONCRE', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3327, 'ARREDONDO PIZARRO MA  ', '', '', 1, 0, 2, 'ARREDONDO PIZARRO MA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3328, 'CHAVEZ ARVIZU LAURA  ', '', '', 1, 0, 2, 'CHAVEZ ARVIZU LAURA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3329, 'LUJAN DUQUE DE ESTRA  ', '', '', 1, 0, 2, 'LUJAN DUQUE DE ESTRA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3330, 'ARMENDARIZ CHAVEZ BE  ', '', '', 1, 0, 2, 'ARMENDARIZ CHAVEZ BE', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3331, 'PACHECO HERNANDEZ JO  ', '', '', 1, 0, 2, 'PACHECO HERNANDEZ JO', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3332, 'RECICLAJE Y RECUPERA  ', '', '', 1, 0, 2, 'RECICLAJE Y RECUPERA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3333, 'MARTINEZ A JESUS VIC  ', '', '', 1, 0, 2, 'MARTINEZ A JESUS VIC', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3335, 'VERDUZCO S. SERGIO R  ', '', '', 1, 0, 2, 'VERDUZCO S. SERGIO R', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3337, 'SANCHEZ PUENTES SANT  ', '', '', 1, 0, 2, 'SANCHEZ PUENTES SANT', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3339, 'GUTIERREZ GUTIERREZ  ', '', '', 1, 0, 2, 'GUTIERREZ GUTIERREZ', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3340, 'HERNANDEZ MORALES MA  ', '', '', 1, 0, 2, 'HERNANDEZ MORALES MA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3341, 'ASESORIA MANUFACTURA  ', '', '', 1, 0, 2, 'ASESORIA MANUFACTURA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3342, 'MANUFACTURAS INDUSTR  ', '', '', 1, 0, 2, 'MANUFACTURAS INDUSTR', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3343, 'DURAN DORA LILIA  ', '', '', 1, 0, 2, 'DURAN DORA LILIA', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3344, 'GONZALEZ RIVAS AZUCE  ', '', '', 1, 0, 2, 'GONZALEZ RIVAS AZUCE', '', '', '', 'MANUEL J. GLOUTHIER', '10110', '', '', '', 'COL. JUAREZ NUEVO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3350, 'PROTRANS DE MEXICO S  ', '', '', 1, 0, 2, 'PROTRANS DE MEXICO S', '', '', '', 'C. IDAHO', '14', '', '', '', 'COL. NAPOLES', 'ND', 'JALISCO', '3810'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3362, 'VICTORY PACKAGING DE  ', '', '', 1, 0, 2, 'VICTORY PACKAGING DE', '', '', '', 'AV JUAN PABLO II', '2750', '', '', '', 'PROFESORA MARIA MARTINEZ', 'JUAREZ', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3383, 'INTERNATIONAL PAPER  ', '', '', 1, 0, 2, 'INTERNATIONAL PAPER', '', '', '', 'MONTES URALES', '723 PH', '', '', '', 'LOMAS DE CHAPULTEPEC', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3385, 'LX PLASTICOS DE JUAR  ', '', '', 1, 0, 2, 'LX PLASTICOS DE JUAR', '', '', '', 'ENRIQUE PINONCELLI', '8651', '', '', '', 'PARQUE IND AEROJUAREZ', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3391, 'AMEX MEXICANA S.A. D  ', '', '', 1, 0, 2, 'AMEX MEXICANA S.A. D', '', '', '', 'NEPTUNO', '1825', '', '', '', 'COL. SATELITE', 'JUAREZ', 'JALISCO', '32540'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3402, 'ALMACEN LOGISTICO DE  ', '', '', 1, 0, 2, 'ALMACEN LOGISTICO DE', '', '', '', 'JUMANOS', '940', '', '', '', 'HEROES DE MEXICO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3408, 'SPAT MAIL, S.A DE C.  ', '', '', 1, 0, 2, 'SPAT MAIL, S.A DE C.', '', '', '', 'AV. QUINTA NORTE', '301', '', '', '', 'CENTRO', 'DELICIAS', 'JALISCO', '33000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3416, 'PRODUCTOS RECICLADOS  ', '', '', 1, 0, 2, 'PRODUCTOS RECICLADOS', '', '', '', 'CARR.JUAREZ PORVENIR', '3050', '', '', '', 'KM 18', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3426, 'BERNAL LARA JOAQUIN  ', '', '', 1, 0, 2, 'BERNAL LARA JOAQUIN', '', '', '', 'BLVD.OSCAR FLORES', '5125', '', '', '', 'LA CUESTA', 'JUAREZ', 'JALISCO', '32650'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3439, 'FAST FOOD LOGISTICA,  ', '', '', 1, 0, 2, 'FAST FOOD LOGISTICA,', '', '', '', 'BLVD.GOMEZ MORIN', '9050', '', '', '', 'PARQUE INDUSTRIAL BERMUDEZ', 'JUAREZ', 'JALISCO', '32470'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3441, 'MAGADAN DIAZ ALEJAND  ', '', '', 1, 0, 2, 'MAGADAN DIAZ ALEJAND', '', '', '', 'BLVD. OSCAR FLORES SANCHEZ', '2812', '', '', '', 'UNIDAD HABITACIONAL BENITO J', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3453, 'ZUÑIGA ESPINDOLA MAR  ', '', '', 1, 0, 2, 'ZUÑIGA ESPINDOLA MAR', '', '', '', 'AVENA', '9006', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3459, 'FERNANDEZ LOPEZ MART  ', '', '', 1, 0, 2, 'FERNANDEZ LOPEZ MART', '', '', '', 'BLVD. TEOFILO BORUNDA', '8681', '', '', '', 'COL. PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3466, 'OPERADORA LUBEAL, S.  ', '', '', 1, 0, 2, 'OPERADORA LUBEAL, S.', '', '', '', 'REAL DE GRIJALVA', '4015', '', '', '', 'FRACC. REAL DEL SOL II', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3475, 'LIBROS FORANEOS S.A.  ', '', '', 1, 0, 2, 'LIBROS FORANEOS S.A.', '', '', '', 'AVENIDA CONSCRIPTO ACCESO 4 CABALLER', '311', '', '', '', 'LOMAS DE SOTELO', 'MIGUEL HIDAL', 'JALISCO', '11200'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3484, 'ORTEGA CAZAREZ JUAN  ', '', '', 1, 0, 2, 'ORTEGA CAZAREZ JUAN', '', '', '', 'BLVD. TOMAS FERNANDEZ', '8255', 'L 10 A', '', '', 'PARQUES', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3485, 'FERNANDEZ ROMO MARIA  ', '', '', 1, 0, 2, 'FERNANDEZ ROMO MARIA', '', '', '', 'CUICUILCO ESQ. GRANITO', '7822', '', '', '', 'MORELOS AZTECA', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3487, 'SIRVIENDO ATENDIENDO  ', '', '', 1, 0, 2, 'SIRVIENDO ATENDIENDO', '', '', '', 'JUAN GRIS', '8807', '', '', '', 'PARAJES DEL SOL', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3490, 'PEREZ CORTES MICAELA  ', '', '', 1, 0, 2, 'PEREZ CORTES MICAELA', '', '', '', 'BLVD. TEOFILO BORUNDA', '8681', '', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '32663'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3497, 'LOUIE GUMBOS SA DE C  ', '', '', 1, 0, 2, 'LOUIE GUMBOS SA DE C', '', '', '', 'RIO PILON', '607', '', '', '', 'DEL VALLE SAN', 'SAN PEDRO GA', 'JALISCO', '66220'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3500, 'SERVICIOS DE COMEDOR  ', '', '', 1, 0, 2, 'SERVICIOS DE COMEDOR', '', '', '', 'HDA. DE SAN NICOLAS PTE', '1610', '', '', '', 'DEL VALLE', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3508, 'EMPRESARIAL AVE DEL  ', '', '', 1, 0, 2, 'EMPRESARIAL AVE DEL', '', '', '', 'MELON', '6718', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3510, 'TOVAR GALAVIZ SERGIO  ', '', '', 1, 0, 2, 'TOVAR GALAVIZ SERGIO', '', '', '', 'TIHUANICO', '8473', '', '', '', 'FRACC. ROMA', 'JUAREZ', 'JALISCO', '32600'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3511, 'MARTINEZ GARDEA MERC  ', '', '', 1, 0, 2, 'MARTINEZ GARDEA MERC', '', '', '', 'HIEDRA', '6954', '', '', '', 'INFONAVIT JUAREZ NUEVO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3512, 'MENDEZ NUÑEZ JESUS M  ', '', '', 1, 0, 2, 'MENDEZ NUÑEZ JESUS M', '', '', '', 'PITAHAYA', '6519', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3514, 'CALZADA LEON JESUS R  ', '', '', 1, 0, 2, 'CALZADA LEON JESUS R', '', '', '', 'PASEO DEL PERAL', '4421', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3516, 'TRANSPORTES ZAPATA,S  ', '', '', 1, 0, 2, 'TRANSPORTES ZAPATA,S', '', '', '', 'FELIPE ANGELES', '852', '', '', '', 'MORELOS ZARAGOZA', 'JUAREZ', 'JALISCO', '32500'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3518, 'ACOSTA ZAPATA BRUNO  ', '', '', 1, 0, 2, 'ACOSTA ZAPATA BRUNO', '', '', '', 'FELIPE ANGELES', '852', '', '', '', 'MORELOS ZARAGOZA', 'JUAREZ', 'JALISCO', '32295'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3519, 'SAENZ GARCIA MARIO A  ', '', '', 1, 0, 2, 'SAENZ GARCIA MARIO A', '', '', '', 'GUSTAVO CASTILLO', '7040', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3527, 'TRANSPORTES GREM, S.  ', '', '', 1, 0, 2, 'TRANSPORTES GREM, S.', '', '', '', 'AV. DE LA RAZA', '5142', '', '', '', 'FRACC. LOS NOGALES', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3528, 'ESCOBEDO JUAN MANUEL  ', '', '', 1, 0, 2, 'ESCOBEDO JUAN MANUEL', '', '', '', 'AV.JUAREZ', '219', '', '', '', 'ND', 'GUADALUPE', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3548, 'RODRIGUEZ PICHARDO I  ', '', '', 1, 0, 2, 'RODRIGUEZ PICHARDO I', '', '', '', 'ND', 'SN', '', '', '', 'BARRIO ALTO', 'GUADALUPE', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3552, 'GONZALEZ FIGUEROA AL  ', '', '', 1, 0, 2, 'GONZALEZ FIGUEROA AL', '', '', '', 'ANT.CAMINO A ZARAGOZA', '1561', '', '', '', 'FIDEL AVILA', 'JUAREZ', 'JALISCO', '32540'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3553, 'DISTRIBUIDORA Y TRAN  ', '', '', 1, 0, 2, 'DISTRIBUIDORA Y TRAN', '', '', '', 'CAMINO DE LAS LOMAS', '4350', '', '', '', 'PARTIDO DOBLADO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3558, 'TRANSPORTE MAQUILADO  ', '', '', 1, 0, 2, 'TRANSPORTE MAQUILADO', '', '', '', 'P.TRIUNFO DE LA REPUBLICA', '5621', '', '', '', 'ALAMOS DE SAN LORENZO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3562, 'MORITA HOLGUIN MIGUE  ', '', '', 1, 0, 2, 'MORITA HOLGUIN MIGUE', '', '', '', 'CALLE 20', '2303', '', '', '', 'COL. VILLA JUAREZ', 'CHIHUAHUA', 'JALISCO', '31090'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3565, 'SERVICIOS QUILOR, S.  ', '', '', 1, 0, 2, 'SERVICIOS QUILOR, S.', '', '', '', 'DINA RICO', '7712', '', '', '', 'INDEPENDENCIA 2', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3586, 'VILLAGOMEZ JUAN PABL  ', '', '', 1, 0, 2, 'VILLAGOMEZ JUAN PABL', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3588, 'FERRETERIA MALI  ', '', '', 1, 0, 2, 'FERRETERIA MALI', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3592, 'LEON FUENTES ALEJAND  ', '', '', 1, 0, 2, 'LEON FUENTES ALEJAND', '', '', '', 'DIAZ DE BUSTAMANTE', '2820', '', '', '', 'INDEPENDENCIA No. 2', 'ND', 'JALISCO', '32670'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3596, 'LOPEZ GONZALEZ ROBER  ', '', '', 1, 0, 2, 'LOPEZ GONZALEZ ROBER', '', '', '', 'CIRUELO', '6457', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3600, 'MARISCOS DEL MAR (BR  ', '', '', 1, 0, 2, 'MARISCOS DEL MAR (BR', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3606, 'TORTILLERIA UNIVERSI  ', '', '', 1, 0, 2, 'TORTILLERIA UNIVERSI', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3607, 'TORTILLERIA SUSY  ', '', '', 1, 0, 2, 'TORTILLERIA SUSY', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3608, 'TORTILLERIA LOS TRAV  ', '', '', 1, 0, 2, 'TORTILLERIA LOS TRAV', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3609, 'TORTILLERIA LA MATIT  ', '', '', 1, 0, 2, 'TORTILLERIA LA MATIT', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3610, 'TORTILLERIA ALEJANDR  ', '', '', 1, 0, 2, 'TORTILLERIA ALEJANDR', '', '', '', 'COMPOSITORES', 'SN', '', '', '', 'CAMPANARIO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3612, 'TORTILLERIA EL PUAS  ', '', '', 1, 0, 2, 'TORTILLERIA EL PUAS', '', '', '', 'FELIPE ANGELES', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3613, 'ROGUPE SA DE CV  ', '', '', 1, 0, 2, 'ROGUPE SA DE CV', '', '', '', 'HIGO', '7118', '', '', '', 'EL GRANJERO', 'JUAREZ', 'JALISCO', '32690'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3614, 'LOYA MORALES LUIS CA  ', '', '', 1, 0, 2, 'LOYA MORALES LUIS CA', '', '', '', 'GRAL. ANASTACIO PANTOJA', '1009', '', '', '', 'OASIS REVOLUCION', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3619, 'OPERACIONES  ', '', '', 1, 0, 2, 'OPERACIONES', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3620, 'FUNDACION INDIOS A.C  ', '', '', 1, 0, 2, 'FUNDACION INDIOS A.C', '', '', '', 'TAPACHULA', '591', '', '', '', 'COLINA DE JUAREZ', 'JUAREZ', 'JALISCO', '32680'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3627, 'TORTILLERIA SAN JUAN  ', '', '', 1, 0, 2, 'TORTILLERIA SAN JUAN', '', '', '', 'DURANGO', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3635, 'JORISPORTEO , S.A. D  ', '', '', 1, 0, 2, 'JORISPORTEO , S.A. D', '', '', '', 'AVENIDA DE LAS INDUSTRIAS', '6500', '', '', '', 'NOMBRE DE DIOS', 'CHIHUAHUA', 'JALISCO', '31150'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3655, 'LINEAS DE CD.JUAREZ,  ', '', '', 1, 0, 2, 'LINEAS DE CD.JUAREZ,', '', '', '', 'FRAY MARCOS DE NIZA', '539', '', '', '', 'DEL FUTURO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3656, 'FASI TECNOLOGIAS S D  ', '', '', 1, 0, 2, 'FASI TECNOLOGIAS S D', '', '', '', 'ALFONZO GARZON S.', '10648', '', '', '', 'CAMPESINA', 'JUAREZ', 'JALISCO', '32675'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3659, 'RAPID INDUSTRIES DE  ', '', '', 1, 0, 2, 'RAPID INDUSTRIES DE', '', '', '', 'AV. EJE VIAL JUAN GABRIEL', '2150', '', '', '', 'MELCHOR OCAMPO', 'JUAREZ', 'JALISCO', '32380'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3673, 'LUCIO EDGAR  ', '', '', 1, 0, 2, 'LUCIO EDGAR', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3674, 'LUCIO LUIS  ', '', '', 1, 0, 2, 'LUCIO LUIS', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3701, 'RONQUILLO CARLOS  ', '', '', 1, 0, 2, 'RONQUILLO CARLOS', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3729, 'AMCOR RIGID PLASTICS  ', '', '', 1, 0, 2, 'AMCOR RIGID PLASTICS', '', '', '', 'ROGELIO GONZALEZ CABALLERO', '850', '', '', '', 'PARQUE INDUSTRIAL STIVA. AER', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3732, 'CAMPOS SALAZAR VALER  ', '', '', 1, 0, 2, 'CAMPOS SALAZAR VALER', '', '', '', 'SEVERA OROSTEGUI', '2727', '', '', '', 'SIMONA BARBA', 'JUAREZ', 'JALISCO', '32590'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3742, 'SERVICIOS Y SUMINIST  ', '', '', 1, 0, 2, 'SERVICIOS Y SUMINIST', '', '', '', 'VALLE DEL SOL', '1573', '', '', '', 'EJIDO ASALVARCAR', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3746, 'RECICLADORA CLEANMEX  ', '', '', 1, 0, 2, 'RECICLADORA CLEANMEX', '', '', '', 'PEDRO MENESES HOYOS', '7554', '', '', '', 'PARTIDO IGLESIAS', 'JUAREZ', 'JALISCO', '32528'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3757, 'ALIMENTOS PROCESADOS  ', '', '', 1, 0, 2, 'ALIMENTOS PROCESADOS', '', '', '', 'BLVD. TOMAS FERNANDEZ', '7818', '', '', '', 'CAMPESTRE SUR', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3762, 'RESTAURANTES HERREGU  ', '', '', 1, 0, 2, 'RESTAURANTES HERREGU', '', '', '', 'CALLE 7A', '602', '', '', '', 'CENTRO', 'CHIHUAHUA', 'JALISCO', '31000'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3777, 'RAMIREZ DAVILA CIPRI  ', '', '', 1, 0, 2, 'RAMIREZ DAVILA CIPRI', '', '', '', 'DE LA BARRANCA', '9170', '', '', '', 'PRADERAS DE LA SIERRA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3778, 'SERVICIO PAN AMERICA  ', '', '', 1, 0, 2, 'SERVICIO PAN AMERICA', '', '', '', 'AVE. ADOLFO LOPEZ MATEOS', '', 'NORTE', '', '', 'FRACC. LA PLAYA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3780, 'DISTRIBUIDORA DE PRO  ', '', '', 1, 0, 2, 'DISTRIBUIDORA DE PRO', '', '', '', 'AV. LOPEZ MATEOS', '1506', '', '', '', 'NOGALES', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3781, 'CORPORATIVO EMPRESAR  ', '', '', 1, 0, 2, 'CORPORATIVO EMPRESAR', '', '', '', 'AVE. JUAREZ', '219', '', '', '', 'CENTRO', 'GUADALUPE', 'JALISCO', '32740'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3782, 'CHACON GUTIERREZ MAR  ', '', '', 1, 0, 2, 'CHACON GUTIERREZ MAR', '', '', '', 'AGUA CALIENTE', '7119', '', '', '', 'PRADERA DORADA', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3784, 'PARRA MEDINA JOSE LU  ', '', '', 1, 0, 2, 'PARRA MEDINA JOSE LU', '', '', '', 'CARTAGENA', '5046', '', '', '', 'SAN ANTONIO', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3786, 'RIVERA DE AVILA JUAN  ', '', '', 1, 0, 2, 'RIVERA DE AVILA JUAN', '', '', '', 'TRES CUMBRES', '1121', '', '', '', 'MORELOS TRES', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3789, 'VRP TRANSPORTES DE M  ', '', '', 1, 0, 2, 'VRP TRANSPORTES DE M', '', '', '', 'BOULEVARD OSCAR FLORES SANCHEZ', '10061', '', '', '', 'PUENTE ALTO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3791, 'GIRES BURCIAGA GERAR  ', '', '', 1, 0, 2, 'GIRES BURCIAGA GERAR', '', '', '', 'PASEO DE LOS COMPOSITORES', '1522', '', '', '', 'REAL DEL CAMPANARIO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3792, 'LEYVA MALDONADO ALMA  ', '', '', 1, 0, 2, 'LEYVA MALDONADO ALMA', '', '', '', 'CAMINO LOMAS Y PUENTE DE HERCULES', '7502', '', '', '', 'FRACC. LA JOYA', 'JUAREZ', 'JALISCO', '32330'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3793, 'GALINDO MARTINEZ JOB  ', '', '', 1, 0, 2, 'GALINDO MARTINEZ JOB', '', '', '', 'FELIPE ANGELES ENTRE MARTIN LOPEZ', '2603', '', '', '', 'Y PABLO LOPEZ GRANJAS DE CHA', 'ND', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3794, 'MARTINEZ DIAZ ALEJAN  ', '', '', 1, 0, 2, 'MARTINEZ DIAZ ALEJAN', '', '', '', 'CERRO DEL CRESTON', '6311', '', '', '', 'LOMAS DE SAN JOSE', 'JUAREZ', 'JALISCO', '32680'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3795, 'TORTILLERIA BETTY DE  ', '', '', 1, 0, 2, 'TORTILLERIA BETTY DE', '', '', '', 'COTUFA', '6409', '', '', '', 'LUCIO BLANCO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3799, 'ESCOBAR MARTINES RAU  ', '', '', 1, 0, 2, 'ESCOBAR MARTINES RAU', '', '', '', 'MONTE DE ARAGON', '1818', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3802, 'BARRIOS TORRES JUAN  ', '', '', 1, 0, 2, 'BARRIOS TORRES JUAN', '', '', '', 'AEROMOZA', '9366', '', '', '', 'JARDINES DEL AEROPUERTO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3806, 'TORTILLERIA ROMA  ', '', '', 1, 0, 2, 'TORTILLERIA ROMA', '', '', '', 'RANCHO EL PICACHO', '1570', '', '', '', 'LA PERLA', 'JUAREZ', 'JALISCO', '32590'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3812, 'CENTRO COMERCIAL COL  ', '', '', 1, 0, 2, 'CENTRO COMERCIAL COL', '', '', '', 'R VELARDE', '243', '', '', '', 'CENTRO', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3816, 'NUEVA WAL MART DE ME  ', '', '', 1, 0, 2, 'NUEVA WAL MART DE ME', '', '', '', 'AV. NEXTENGO', '78', '', '', '', 'SANTA CRUZ ACAYUCAN', 'AZCAPOTZALCO', 'JALISCO', ''
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3821, 'MICROSIP  ', '', '', 1, 0, 2, 'MICROSIP', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3822, 'NOTAS POR FACTURAR  ', '', '', 1, 0, 2, 'NOTAS POR FACTURAR', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 3823, 'CREDI CONTADO  ', '', '', 1, 0, 2, 'CREDI CONTADO', '', '', '', 'ND', 'SN', '', '', '', 'ND', 'JUAREZ', 'JALISCO', '1'
EXECUTE [dbo].[PG_CI_CLIENTE_TMK] 0, 0, 0, 9999, 'AJUSTE AJUSTE ', 'AJUSTE', '', 1, 0, 2, 'AJUSTE', 'AJUSTE', '', '', 'X', '0', '0', 'X', 'X', '2DO BARRIO', 'AHUMADA', 'CHIHUAHUA', '32800'

*/
GO

	
-- ===============================================
SET NOCOUNT OFF
-- ===============================================


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
