-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	ADG18_AdministradoraGas
-- // MODULO:			
-- // OPERACION:		LIBERACION // STORED PROCEDURE
-- ////////////////////////////////////////////////////////////// 

USE [ADG18_AdministradoraGas_V9999_R0] 
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // USUARIOS
-- //////////////////////////////////////////////////////////////
-- SELECT * FROM USUARIO WHERE K_USUARIO>999


DELETE 
FROM	[SITIO_USUARIO_X_UO]
WHERE	K_USUARIO>999


DELETE 
FROM	USUARIO 
WHERE	K_USUARIO>999


-- //////////////////////////////////////////////////////////////


EXECUTE [dbo].[PG_CI_USUARIO]	0,2006,0, 1001, 'Victor Gonzalez Ramirez',		'DIRECCION',		'VGR', 150, 1, 'VGonzalez@tomza.com',	'VIGO', '357689', '04/MAR/2019',	1, 1,NULL
EXECUTE [dbo].[PG_CI_USUARIO]	0,2006,0, 1002, 'Miguel H. Toquica Botia',		'VENTAS',			'MTB', 160, 1, 'MToquica.B@tomza.com',	'TOQI', '468790', '04/MAR/2019',	1, 1,NULL
EXECUTE [dbo].[PG_CI_USUARIO]	0,2006,0, 1003, 'ALEJANDRA ROMERO VILLEGAS',	'ADMINISTRADORAS',	'ARV', 170, 1, 'Gromero.v@tomza.com',   'ARV',  '579801', '04/MAR/2019',	1, 1,NULL

GO


UPDATE	USUARIO 
SET		CONTRASENA=123456
WHERE	K_USUARIO>999
GO
/*
LOGIN_ID	CONTRASENA
1001	VIGO		123456
1002	TOQI		123456
1003	ARV			123456
*/





-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- SELECT * FROM [SITIO_USUARIO_X_UO]



EXECUTE [dbo].[PG_CI_SITIO_USUARIO_X_UO] 0, 2006, 0, 1001, 13, 1		-- ACCESO >>> #13 UNIGAS MATRIZ
EXECUTE [dbo].[PG_CI_SITIO_USUARIO_X_UO] 0, 2006, 0, 1002, 13, 1		-- ACCESO >>> #13 UNIGAS MATRIZ
EXECUTE [dbo].[PG_CI_SITIO_USUARIO_X_UO] 0, 2006, 0, 1003, 13, 1		-- ACCESO >>> #13 UNIGAS MATRIZ


-- ===============================================
SET NOCOUNT OFF
-- ===============================================



-- //////////////////////////////////////////////////////////////
-- // SYS_PERFIL_DEFINICION
-- //////////////////////////////////////////////////////////////
-- SELECT * FROM [SYS_PERFIL_DEFINICION]
-- //////////////////////////////////////////////////////////////
-- K_SYS_PERFIL_ROL = #0 NINGUNO | #1 FULL CONTROL | #2 CORDINACION | #3 OPERACION | #4 CONSULTA


-- ===============================================
SET NOCOUNT ON
-- ===============================================

-- SELECT * FROM SYS_PERFIL_DEFINICION

-- SELECT * FROM [SYS_PERFIL_DEFINICION_ACCION]


DELETE FROM SYS_PERFIL_DEFINICION_ACCION

DELETE FROM SYS_PERFIL_DEFINICION

GO



 -- =========================================== CARGA INICIAL X USUARIO >> #99/FEG >> FRANCISCO ESTEBAN
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    99, 0, 'FO_BITACORA_COMISION';
GO
 -- =========================================== CARGA INICIAL X USUARIO >> #1001/VIGO >> VICTOR GONZALEZ
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 2, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 1, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 1, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 2, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 2, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 6, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 5, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 5, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 5, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 1, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 5, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 5, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 1, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 2, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 1, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 1, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 5, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1001, 4, 'FO_BITACORA_COMISION';
GO
 -- =========================================== CARGA INICIAL X USUARIO >> #1002/TOQI >> MIGUEL TOQUICA
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 2, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 1, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 1, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 2, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 2, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 6, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 5, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 5, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 5, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 2, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 5, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 5, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 1, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 2, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 1, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 1, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 5, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1002, 4, 'FO_BITACORA_COMISION';
GO
 -- =========================================== CARGA INICIAL X USUARIO >> #1003/AROM >> ALEJANDRA ROMERO
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 6, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 5, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 5, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 5, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 5, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 5, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 3, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 5, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    1003, 4, 'FO_BITACORA_COMISION';
GO
 -- =========================================== CARGA INICIAL X USUARIO >> #111/CZG >> CYNTHIA ZAMARRON
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    111, 1, 'FO_BITACORA_COMISION';
GO
 -- =========================================== CARGA INICIAL X USUARIO >> #169/FEG >> HECTOR GONZALEZ
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    169, 1, 'FO_BITACORA_COMISION';
GO
 -- =========================================== CARGA INICIAL X USUARIO >> #177/JPP >> JAVIER PEDROZA
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_NOMBRE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_PRODUCTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_TASA_IMPUESTO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_PRECIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_CARGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_CONDICION_COMERCIAL';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_LECTURA';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_SITIO_CONTROL_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_RENGLON_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_GENERA_RECIBO_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_GENERA_ESTADO_CUENTA_PDF';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_PAGO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_APLICAR_PAGO_CLIENTE';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_PAGO_RECIBO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_CLIENTE_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_BITACORA_DESCONEXION_RECONEXION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_ALMACEN_SITIO';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_MOVIMIENTO_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_HISTORIA_ALMACEN';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_SITIO_ADMINISTRADOR';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_GENERAR_COMISION';
EXECUTE [dbo].[PG_CI_SYS_PERFIL_DEFINICION] 0, 2006,    177, 1, 'FO_BITACORA_COMISION';
GO


GO

-- ===============================================
SET NOCOUNT OFF
-- ===============================================


-- ////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////
