-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			ORGANIZACION / RAZON_SOCIAL 
-- // OPERACION:		LIBERACION / CARGA INICIAL
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO


-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
--	

DELETE  
FROM [dbo].[RAZON_SOCIAL]
GO

-- //////////////////////////////////////////////////////////////
-- SELECT * FROM RAZON_SOCIAL

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_RAZON_SOCIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_RAZON_SOCIAL]
GO


CREATE PROCEDURE [dbo].[PG_CI_RAZON_SOCIAL]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_RAZON_SOCIAL			INT,
	@PP_D_RAZON_SOCIAL			VARCHAR(100),
	@PP_S_RAZON_SOCIAL			VARCHAR(10),
--	@PP_K_ESTATUS_RAZON_SOCIAL	INT,
	@PP_K_TIPO_RAZON_SOCIAL		INT,
	@PP_RAZON_SOCIAL			VARCHAR(100),
	@PP_RFC_RAZON_SOCIAL		VARCHAR(100),
	@PP_CURP					VARCHAR(100),
	@PP_CORREO					VARCHAR(100),
	@PP_TELEFONO				VARCHAR(100),
	@PP_CALLE					VARCHAR(255),
	@PP_NUMERO_EXTERIOR			VARCHAR(10),
	@PP_NUMERO_INTERIOR			VARCHAR(10),
	@PP_COLONIA					VARCHAR(100),
	@PP_POBLACION				VARCHAR(100),
	@PP_CP						VARCHAR(10),
	@PP_MUNICIPIO				VARCHAR(100),
	@PP_K_REGION				INT
	-- ===========================
AS			
	-- K_USUARIO // 0	SYS/SETUP
	DECLARE @VP_K_USUARIO_ACCION		INT = 0 
	DECLARE @VP_O_RAZON_SOCIAL			INT = 0

	-- ===========================
	
	DECLARE @PP_K_ESTATUS_RAZON_SOCIAL	INT
	
	SET		@PP_K_ESTATUS_RAZON_SOCIAL	=	( @PP_K_RAZON_SOCIAL % 4 )

	-- ===========================

	INSERT INTO RAZON_SOCIAL
			(	[K_RAZON_SOCIAL],
				[D_RAZON_SOCIAL], [S_RAZON_SOCIAL], [O_RAZON_SOCIAL],
				[K_ESTATUS_RAZON_SOCIAL], [K_TIPO_RAZON_SOCIAL],
				-- ===========================
				[RAZON_SOCIAL],
				[RFC_RAZON_SOCIAL], [CURP], 
				[CORREO], [TELEFONO], 
				[CALLE], [NUMERO_EXTERIOR], [NUMERO_INTERIOR], 
				[COLONIA], [POBLACION],
				[CP],[MUNICIPIO],[K_REGION],
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
		VALUES	
			(	@PP_K_RAZON_SOCIAL,
				@PP_D_RAZON_SOCIAL, @PP_S_RAZON_SOCIAL, @VP_O_RAZON_SOCIAL, 
				@PP_K_ESTATUS_RAZON_SOCIAL, @PP_K_TIPO_RAZON_SOCIAL,
				-- ===========================
				@PP_RAZON_SOCIAL,
				@PP_RFC_RAZON_SOCIAL, @PP_CURP, 
				@PP_CORREO,	@PP_TELEFONO, 
				@PP_CALLE, @PP_NUMERO_EXTERIOR, @PP_NUMERO_INTERIOR,
				@PP_COLONIA, @PP_POBLACION,
				@PP_CP, @PP_MUNICIPIO,@PP_K_REGION,	
				-- ===========================
				@VP_K_USUARIO_ACCION, GETDATE(), @VP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )
		
	-- //////////////////////////////////////////////////////////////
GO


-- ===============================================
SET NOCOUNT ON
-- ===============================================


-- ======================================== [dbo].[PG_CI_RAZON_SOCIAL] 

EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 0, '( SIN RAZON SOCIAL )', 'XXXXX', 0,'SIN ASIGNAR', 'XXX000000XX0', '', '', '', '', '', '', '', '', '12345', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 86, 'GAS Y PETROLEO / GOLFO', 'GYPGF', 3,'COMPAÑIA IMPORTADORA DE GAS Y PETROLEO DEL GOLFO SA DE CV', 'IGP160201NK5', '', '', '', 'AV SAN FELIPE', '807', 'S/N', 'SAN FELIPE II', 'CHIHUAHUA', '31203', 'CHIHUAHUA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 84, 'GAS Y PRETROLEO / JUAREZ', 'GYPJZ', 3,'COMPAÑIA IMPORTADORA DE GAS Y PRETROLEO DE JUAREZ, SA DE CV', 'IGP160201P62', '', '', '', 'AV SAN FELIPE', '807', 'SN', 'SAN FELIPE II', 'SN', '31203', 'CHIHUAHUA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 6, 'MEXICANA DE GAS', 'MEXGS', 1,'COMPAÑIA MEXICANA DE GAS COMBUSTIBLE SA DE CV', 'MGC471027M17', '', '', '', 'KM 22.5 AUTOPISTA MEXICO PUEBLA', 'S/N', '', 'SANTA CATARINA YECAHUIZOTL', 'TLAHUAC', '53100', 'TLAHUAC', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 10, 'BUTEP', 'BUTEP', 1,'GAS BUTEP S.A. DE C.V.', 'GBU7109148V4', '', '', '', 'AV. MORELOS', '51', '', 'CENTRO', 'TEPATITLAN', '47600', 'TEPATITLAN', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 11, 'CHAPULTEPEC (GAS)', 'CHAPU', 1,'GAS CHAPULTEPEC SA DE CV', 'GCA5411048Z4', '', '', '', 'SIDERURGIA', 'S/N', '', 'INDUSTRIAL XALOSTOC', 'ECATEPEC DE MORELOS', '55348', 'ECATEPEC DE MORELOS', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 12, 'GAS COMERCIAL / NUEVO CASAS GRANDES', 'GCNCG', 1,'GAS COMERCIAL DE NUEVO CASAS GRANDES SA DE CV', 'GCN6105309I5', '', '', '', 'C SUECO KM 189 42', 'S/N', '', 'OBRERA', 'NUEVO CASAS GRANDES', '31750', 'NUEVO CASAS GRANDES', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 13, 'GAS COMERCIAL / VILLA AHUMADA', 'GCVAH', 1,'GAS COMERCIAL DE VILLA AHUMADA SA DE CV', 'GCV610502NY0', '', '', '', 'CARR PANAMERICA KM 17', 'S/N', '', 'AMPLIACION AEROPUERTO', 'JUAREZ', '32690', 'JUAREZ', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 53, 'TENABO (GAS)', 'GSILZ', 1,'GAS DE TENABO S.A. DE C.V.', 'GTE031106PU9', '', '', '', 'CARRETERA CAMPECHE MERIDA KM 35 MAS 200', 'S/N', '', 'SIN COLONIA', 'TENABO', '24700', 'TENABO', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 16, 'SILZA (GAS)', 'GSLZA', 1,'GAS SILZA S.A. DE C.V.', 'GSI900821UG1', '', '', '', 'CARRETERA A TECATE KM 27.5', 'S/N', '', 'LA MESA', 'TIJUANA', '22105', 'TIJUANA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 89, 'TITANIUM (GAS)', 'TITAN', 1,'GAS TITANIUM S.A. DE C.V.', 'GTI110912122', '', '', '', 'SAN ISIDRO LA SOLEDAD KM. 19.8', 'S/N', 'S/N', 'N/D', 'PALO ALTO', '20330', 'EL LLANO', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 19, 'TOMZA / MEXICO (GAS)', 'GTMEX', 1,'GAS TOMZA DE MEXICO S.A. DE C.V.', 'GTM020909DJ2', '', '', '', 'PARQUE INDUSTRIAL TEPEJI LT 183 MZ 24', 'S/N', '', 'PARQUE INDUSTRIAL TEPEJI', 'TEPEJI DEL RIO', '42850', 'TEPEJI DEL RIO DE OCAMPO', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 15, 'TOMZA / PUEBLA (GAS)', 'GTPUE', 1,'GAS TOMZA DE PUEBLA, SA DE CV', 'GPR960815HJA', '', '', '', 'KM. 134.8 AUTOPISTA MEXICO-ORIZABA', 'S/N', '', 'PARQUE INDUSTRIAL SAN FELIPE CHACHAPA', 'AMOZOC', '72980', 'AMOZOC', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 45, 'TOMZA / YUCATAN (GAS)', 'GTYUC', 1,'GAS TOMZA DE YUCATAN S.A. DE C.V.', 'GTY030728BA4', '', '', '', 'CARRETERA UMAN KINCHIL KM 15 MAS 500', 'S/N', '', 'SIN COLONIA', 'SAMAHIL', '97810', 'SAMAHIL', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 21, 'URIBE ACAPULCO (GAS)', 'URIBE', 1,'GAS URIBE DE ACAPULCO SA DE CV', 'GUA8501025D6', '', '', '', 'BOULEVARD TOMAS FERNANDEZ', '8255', '11B', 'LOS PARQUES', 'JUAREZ', '32440', 'JUAREZ', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 49, 'VULCANO (GAS)', 'VULCN', 1,'GAS VULCANO SA DE CV', 'GVU9912072H9', '', '', '', 'CARR. AL FRESNITO KM', 'S/N', '', 'CENTRO', 'CD GUZMAN', '49100', 'ZAPOTLAN EL GRANDE', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 23, 'GAS Y SERVICIO', 'GASYS', 1,'GAS Y SERVICIO SA DE CV', 'GSE520604IT5', '', '', '', 'AV SAN JOSE', '55', '', 'LAZARO CARDENAS', 'HERMILIO MENA', '54189', 'TLALNEPANTLA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 24, 'ZARAGOZA OJINAGA (GAS)', 'GZAOJ', 1,'GAS ZARAGOZA EN OJINAGA S.A. DE C.V.', 'GZO8712026P7', '', '', '', 'JUSTO SIERRA', '300', 'S/N', 'LINDA VISTA', 'OJINAGA', '32885', 'OJINAGA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 25, 'GASOMATICO', 'GSOMA', 1,'GASOMATICO S.A. DE C.V.', 'GAS710629HU3', '', '', '', 'AV. SAN JOSE', '7', 'BIS', 'SAN JUAN IXHUATEPEC', 'TLALNEPANTLA DE BAZ', '54180', 'TLALNEPANTLA DE BAZ', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 36, 'HIDROGAS / AGUA PRIETA', 'HIAGP', 1,'HIDRO GAS DE AGUA PRIETA SA DE CV', 'HGA7512092G9', '', '', '', 'CARRETERA A NACOZARI KM. 5 1.2', 'S/N', '', 'EJIDAL', 'AGUA PRIETA', '84259', 'AGUA PRIETA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 26, 'HIDROGAS / ACAPULCO', 'HIACA', 1,'HIDROGAS ACAPULCO SA DE CV', 'HAC8205109V4', '', '', '', 'BOULEVARD TOMAS FERNANDEZ', '8255', '11B', 'LOS PARQUES', 'JUAREZ', '32440', 'JUAREZ', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 28, 'HIDROGAS / CHIHUAHUA', 'HICHI', 1,'HIDROGAS DE CHIHUAHUA S.A. DE C.V.', 'HCI8401303N0', '', '', '', 'AV. FUENTES MARES KM. 1', 'S/N', '', 'SANTA ROSA', 'CHIHUAHUA', '31050', 'CHIHUAHUA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 47, 'HOLBOX ', 'HOLBX', 1,'HOLBOX GAS, S.A. DE C.V.', 'HGA0301158L7', '', '', '', 'AV. INDUSTRIAL MANZANA 27', 'LOTE 06', '', 'REG 97', 'BENITO JUAREZ', '77530', 'BENITO JUAREZ', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 30, 'INZA', 'INZA', 8,'INDUSTRIAS ZARAGOZA DIVISION PRODUCTOS METALICOS, S.A. DE C.V.', 'IZD830721361', '', '', '', 'CARR. PANAMERICANA', 'KM 17', '', 'NUEVO HIPODROMO', 'CD JUAREZ', '32685', 'JUAREZ', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 65, 'MAMEME (GAS)', 'MAMEM', 1,'MAMEME GAS, S.A. DE C.V.', 'MGA0902271A0', '', '', '', 'CARRETERA TALA SANTA CRUZ KM 7.40', 'S/N', '', 'SAN JUAN DE LOS ARCOS', 'TALA', '45331', 'TALA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 42, 'UNIGAS', 'UNIGS', 1,'UNIGAS SA DE CV', 'UGA810602EX1', '', '', '', 'AV SAN JOSE', '7', '', 'LA PRESA', 'TLALNEPANTLA', '54180', 'TLALNEPANTLA', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 1, 'AEROSILZA', 'AEROS', 6,'AEROSILZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 2, 'AEROTOMZA', 'AEROT', 6,'AEROTOMZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 3, 'APPLEMEX', 'APPMX', 99,'APPLEMEX S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 4, 'ASPTA', 'ASPTA', 8,'ASESORIA Y SERVICIOS PROFECIONALES TECNICOS Y ADMINISTRATIVOS S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 5, 'COLECCION ARTISTICA SILZA', 'CARTS', 99,'COLECCION ARTISTICA SILZA S.A DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 7, 'COMPAÑIA MEXICANA DE GAS COMBUSTIBLE S.A. DE C.V. TEHUACAN', 'MEXTE', 1,'COMPAÑIA MEXICANA DE GAS COMBUSTIBLE S.A. DE C.V. TEHUACAN', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 8, 'DESARROLLOS ESMERALDA', 'ESMER', 4,'DESARROLLOS ESMERALDA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 9, 'ESTACIONES SERVICIO SILZA', 'SERVS', 8,'ESTACIONES DE SERVICIO SILZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 14, 'DEL PACIFICO (GAS)', 'GSPAC', 1,'GAS DEL PACIFICO S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 17, 'SILZA DE MEXICO (GAS)', 'GSILM', 1,'GAS SILZA DE MEXICO S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 18, 'TOMZA DE LA LAGUNA (GAS)', 'GTLAG', 1,'GAS TOMZA DE LA LAGUNA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 20, 'TOMZA DEL CARIBE (GAS)', 'GTCAR', 1,'GAS TOMZA DEL CARIBE S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 22, 'VEHICULAR SILZA (GAS)', 'GVSIL', 1,'GAS VEHICULAR SILZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 29, 'HIDROGAS DE OJINAGA', 'HOJIN', 1,'HIDROGAS DE OJINAGA S.A. DE CV', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 31, 'INMOBILIARIA DE MEXICO GINZA', 'IMGIN', 4,'INMOBILIARIA DE MEXICO GINZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 32, 'INMOBILIARIA LOS MEDANOS', 'IMEDA', 4,'INMOBILIARIA LOS MEDANOS S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 33, 'INMOBILIARIA SILZA', 'ISILZ', 4,'INMOBILIARIA SILZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 34, 'INMOBILIARIA TOMZA', 'ITOMZ', 4,'INMOBILIARIA TOMZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 35, 'INMOBILIARIA ZARAGOZA ITO', 'IZARZ', 4,'INMOBILIARIA ZARAGOZA ITO S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 37, 'SR. ENRIQUE ZARAGOZA ITO', 'ENZAI', 5,'SR. ENRIQUE ZARAGOZA ITO.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 38, 'SR. TOMAS ZARAGOZA FUENTES', 'TOZAF', 5,'SR. TOMAS ZARAGOZA FUENTES.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 39, 'SR. TOMAS ZARAGOZA ITO', 'TOZAI', 5,'SR. TOMAS ZARAGOZA ITO.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 40, 'SRITA. SILVIA ZARAGOZA ITO', 'SIZAI', 5,'SRITA. SILVIA ZARAGOZA ITO.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 41, 'TRANSPORTADORA SILZA MX', 'TRSIL', 2,'TRANSPORTADORA SILZA S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 44, 'CORPORACION TOMZA', 'CORTZ', 99,'CORPORACION TOMZA', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 50, 'SUN CITY VENTURES', 'SCVEN', 99,'SUN CITY VENTURES LLC', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 51, 'AMERICAN AIR LODGE LP', 'AMEAL', 99,'AMERICAN AIR LODGE LP', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 52, 'CORPRACION E INVERSIONES TOMZA DE MEXICO', 'CITMX', 99,'CORPRACION E INVERSIONES TOMZA DE MEXICO SA DE CV', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 54, 'TOMZA DE VERACRUZ (GAS)', 'GTVCZ', 1,'GAS TOMZA DE VERACRUZ,S.A. DE C.V.', 'GTV020909KA9', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 57, 'TERMINAL MARITIMA GAS TOMZA', 'TMGTZ', 8,'TERMINAL MARITIMA GAS TOMZA, S.A. DE C.V.', 'TMG050802I47', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 58, 'INMOBILIARES TERMINALES DE GAS 58', 'ITERG', 4,'INMOBILIARES TERMINALES DE GAS, S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 59, 'INMOBILIARIA TERMINALES DE GAS 59', 'ITERG', 4,'INMOBILIARIA TERMINALES DE GAS, S.A. DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 60, 'SRA. MELINA SAMANTHA SANCHEZ SANTILLANA', 'MESSS', 5,'SRA. MELINA SAMANTHA SANCHEZ SANTILLANA', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 61, 'FUNDACION ALBERTO ZARAGOZA 61', 'FALZA', 99,'FUNDACION ALBERTO ZARAGOZA A.C.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 62, 'INMOBILIARIA ERNESIL', 'IERNE', 4,'INMOBILIARIA ERNESIL SA DE CV', 'IER090708TW8', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 63, 'INMOBILIARIA UNIGAS', 'IUNIG', 4,'INMOBILIARIA UNIGAS SA DE CV', 'IUN090708C29', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 64, 'SILVIA ITO VARELA', 'SITVA', 5,'SILVIA ITO VARELA', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 67, 'TRANSPORTADORA SILZA USA', 'TSILZ', 2,'TRANSPORTADORA SILZA USA INC', '0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 69, 'FUNDACION ALBERTO ZARAGOZA 69', 'FALZA', 99,'FUNDACION ALBERTO ZARAGOZA AC', '0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 70, 'INMOBILIAIRA EZI 70', 'IEZIS', 4,'INMOBILIAIRA EZI SA DE CV', 'NA', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 71, 'INMOBILIARIA EZI 71', 'IEZIS', 4,'INMOBILIARIA EZI S.A. DE C.V.', 'ND', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 75, 'TOMZAJET', 'TMJET', 6,'TOMZAJET S.A. DE C.V.', '0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 76, 'TRANSPORTADORA TOMZA', 'TRTOM', 2,'TRANSPORTADORA TOMZA SA DE CV ', 'TTO1406045Z5', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 77, 'GINZA HOLDING', 'GINZA', 99,'GINZA HOLDING INC', '0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 78, 'INMOBILIARIA AVANCE DEL NORTE', 'INAVN', 4,'INMOBILIARIA AVANCE DEL NORTE SA DE CV ', 'IAN0603237V0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 79, 'INMOBILIARIA INDUSTRIAL Y FABRIL', 'INIFA', 4,'INMOBILIARIA INDUSTRIAL Y FABRIL SA DE CV', 'IIF710726E33', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 80, 'PETROLEOS Y GAS DEL GOLFO', 'PGAGO', 3,'PETROLEOS Y GAS DEL GOLFO SA DE CV ', 'PGG1602012Q3', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 81, 'PETROLEOS Y GAS DEL NORTE', 'PGANO', 3,'PETROLEOS Y GAS DEL NORTE SA DE CV ', 'PGN1603079Q3', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 82, 'TOMAS RAUL ZARAGOZA IBARRA', 'TRAZA', 5,'TOMAS RAUL ZARAGOZA IBARRA', 'ZAIT920213EU4', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 83, 'TOMAS RAUL ZARAGOZA IBARRA', 'TRAZA', 5,'TOMAS RAUL ZARAGOZA IBARRA', 'ZAIT920213EU4', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 85, 'CIA IMP DE GAS Y PETROLEO DE TIJUANA', 'IGPTJ', 3,'CIA IMP DE GAS Y PETROLEO DE TIJUANA SA DE CV ', '0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 87, 'TAO', 'CETAO', 8,'COMPAÑIA ESPECIALIZADA TAO SA DE CV ', 'ETA160829LZA', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 88, 'COMPAÑIA IMPORTADORA DE GAS Y PETROLEO', 'CIGYP', 3,'COMPAÑIA IMPORTADORA DE GAS Y PETROLEO S.A DE C.V.', 'N/D', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 90, 'TOMZA DE SINALOA (GAS)', 'GTSIN', 1,'GAS TOMZA DE SINALOA, S.A DE C.V.', 'GTS170327JI0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 91, 'TITANIUM (GAS)', 'TITAN', 1,'GAS TITANIUM S.A DE C.V.', '0', '', '', '', '', '', '', '', '', '', '', 0
EXECUTE [dbo].[PG_CI_RAZON_SOCIAL] 0,0,0, 92, 'HELITOMZA', 'HELIT', 6,'HELITOMZA SA DE CV', 'HEL170330393', '', '', '', '', '', '', '', '', '', '', 0


GO


-- ===============================================
SET NOCOUNT OFF
-- ===============================================



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////



